# autogenerated by buildAutosampler.py, Wed Mar 12 10:51:04 2014

def versionString():
    return 'Autosampler-win7-INTERNAL-win7-1.1.0-11'

def versionNumString():
    return '1.1.0.11'

def buildType():
    return 'INTERNAL'

