#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.0 on Wed Feb 10 16:16:48 2016
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class IsotopeScaling(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: IsotopeScaling.__init__
        wx.Dialog.__init__(self, *args, **kwds)
        self.radio_no_scaling = wx.RadioButton(self, wx.ID_ANY, "No Scaling")
        self.radio_scaling = wx.RadioButton(self, wx.ID_ANY, "")
        self.labScale = wx.StaticText(self, wx.ID_ANY, "Scale")
        self.txtScale = wx.TextCtrl(self, wx.ID_ANY, "")
        self.labOffset = wx.StaticText(self, wx.ID_ANY, "Offset")
        self.txtOffset = wx.TextCtrl(self, wx.ID_ANY, "")
        self.btnLoadFile = wx.Button(self, wx.ID_ANY, "Load Parameters from File")
        self.btnOK = wx.Button(self, wx.ID_ANY, "OK")
        self.btnCancel = wx.Button(self, wx.ID_ANY, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_RADIOBUTTON, self.onNoScaling, self.radio_no_scaling)
        self.Bind(wx.EVT_RADIOBUTTON, self.onScaling, self.radio_scaling)
        self.Bind(wx.EVT_BUTTON, self.onLoadParameters, self.btnLoadFile)
        self.Bind(wx.EVT_BUTTON, self.onOK, self.btnOK)
        self.Bind(wx.EVT_BUTTON, self.onCancel, self.btnCancel)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: IsotopeScaling.__set_properties
        self.SetTitle("Isotope Data Scaling")
        self.txtScale.Enable(False)
        self.txtOffset.Enable(False)
        self.btnLoadFile.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: IsotopeScaling.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.radio_no_scaling, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        sizer_4.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_4, 0, 0, 0)
        sizer_5.Add(self.radio_scaling, 0, wx.ALL, 10)
        sizer_7.Add(self.labScale, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        sizer_7.Add(self.txtScale, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        sizer_6.Add(sizer_7, 1, 0, 0)
        sizer_7_copy.Add(self.labOffset, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        sizer_7_copy.Add(self.txtOffset, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        sizer_6.Add(sizer_7_copy, 1, 0, 0)
        sizer_6.Add(self.btnLoadFile, 0, 0, 0)
        sizer_5.Add(sizer_6, 1, 0, 0)
        sizer_2.Add(sizer_5, 1, 0, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_3.Add(self.btnOK, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_3.Add(self.btnCancel, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_3, 0, 0, 0)
        sizer_1.Add(sizer_2, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def onNoScaling(self, event):  # wxGlade: IsotopeScaling.<event_handler>
        print "Event handler 'onNoScaling' not implemented!"
        event.Skip()

    def onScaling(self, event):  # wxGlade: IsotopeScaling.<event_handler>
        print "Event handler 'onScaling' not implemented!"
        event.Skip()

    def onLoadParameters(self, event):  # wxGlade: IsotopeScaling.<event_handler>
        print "Event handler 'onLoadParameters' not implemented!"
        event.Skip()

    def onOK(self, event):  # wxGlade: IsotopeScaling.<event_handler>
        print "Event handler 'onOK' not implemented!"
        event.Skip()

    def onCancel(self, event):  # wxGlade: IsotopeScaling.<event_handler>
        print "Event handler 'onCancel' not implemented!"
        event.Skip()

# end of class IsotopeScaling
