- name: Download bat
  get_url:
    url: https://github.com/sharkdp/bat/releases/download/v0.11.0/bat_0.11.0_amd64.deb
    dest: /tmp/
  become: yes
  when: update == "false"

- name: Download influxdb
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.7.7_amd64.deb
    dest: /tmp/
  become: yes
  when: update == "false"

- name: Download VncViewer
  get_url:
    url: https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.19.923-Linux-x64.deb
    dest: /tmp/
  become: yes
  when: update == "false"

- name: Download telegraf
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.12.4-1_amd64.deb
    dest: /tmp/
  become: yes
  when: update == "false"

- name: Install downloaded debian packages
  apt:
    deb: '{{ item }}'
    state: present
  with_items:
    - /tmp/bat_0.11.0_amd64.deb
    - /tmp/influxdb_1.7.7_amd64.deb
    - /tmp/VNC-Viewer-6.19.923-Linux-x64.deb
    - /tmp/telegraf_1.12.4-1_amd64.deb
  become: yes
  when: update == "false"

- name: Stop telegraf service
  systemd:
    state: stopped
    name: telegraf
  become: yes
  when: update == "false"

- name: Configure telegraf
  copy:
    src: files/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  become: yes
  when: update == "false"

- name: Start InfluxDB Service service
  systemd:
    state: started
    name: influxdb
  become: yes
  when: update == "false"

- name: Create pigss_data database
  shell: influx -execute 'show databases' | grep pigss_data || influx -execute 'create database pigss_data'
  when: update == "false"

- name: Create telegraf database
  shell: influx -execute 'show databases' | grep telegraf || influx -execute 'create database telegraf'
  when: update == "false"

- name: Start telegraf service
  systemd:
    state: started
    name: telegraf
  become: yes
  when: update == "false"

- name: Download go
  get_url:
    url: https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz
    dest: /tmp/
  become: yes
  when: update == "false"

- name: Install go
  shell: tar -C /usr/local -xzf /tmp/go*.tar.gz warn=False
  become: yes
  when: update == "false"
