#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.0 on Wed Sep 23 10:05:21 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class O2CalDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        kwds["style"] = wx.CAPTION | wx.STAY_ON_TOP | wx.SYSTEM_MENU
        wx.Dialog.__init__(self, *args, **kwds)
        self.labelInfo = wx.StaticText(self, wx.ID_ANY, "")
        self.labelInfo2 = wx.StaticText(self, wx.ID_ANY, "")
        self.labelInfo3 = wx.StaticText(self, wx.ID_ANY, "")
        self.label_1 = wx.StaticText(self, wx.ID_ANY, "O2 Concentration")
        self.txtO2Concentration = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_1_copy = wx.StaticText(self, wx.ID_ANY, "Phase Shift")
        self.labelPhaseShift = wx.StaticText(self, wx.ID_ANY, "", style=wx.ALIGN_CENTER)
        self.label_1_copy_1 = wx.StaticText(self, wx.ID_ANY, "Temperature")
        self.labelTemperature = wx.StaticText(self, wx.ID_ANY, "", style=wx.ALIGN_CENTER)
        self.label_1_copy_2 = wx.StaticText(self, wx.ID_ANY, "O2Pressure")
        self.labelPressure = wx.StaticText(self, wx.ID_ANY, "", style=wx.ALIGN_CENTER)
        self.btnNext = wx.Button(self, wx.ID_ANY, "Next")
        self.btnCancel = wx.Button(self, wx.ID_ANY, "Skip")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnNext, self.btnNext)
        self.Bind(wx.EVT_BUTTON, self.OnCancel, self.btnCancel)
        
    def __set_properties(self):
        self.SetTitle("O2 Sensor Calibration")
        self.labelInfo.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_1.SetMinSize((99, 16))
        self.label_1_copy.SetMinSize((64, 16))
        self.labelPhaseShift.SetMinSize((100, 20))
        self.label_1_copy_1.SetMinSize((76, 16))
        self.labelTemperature.SetMinSize((100, 20))
        self.label_1_copy_2.SetMinSize((65, 16))
        self.labelPressure.SetMinSize((100, 20))
        self.btnNext.Enable(False)
        
    def __do_layout(self):
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(2, 2, 0, 0)
        sizer_3_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.labelInfo, 0, wx.ALL, 10)
        sizer_4.Add(self.labelInfo2, 0, wx.ALL, 10)
        sizer_4.Add(self.labelInfo3, 0, wx.ALL, 10)
        sizer_1.Add(sizer_4, 0, 0, 0)
        sizer_3.Add(self.label_1, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_3.Add(self.txtO2Concentration, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(sizer_3, 1, 0, 0)
        sizer_3_copy.Add(self.label_1_copy, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_3_copy.Add(self.labelPhaseShift, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(sizer_3_copy, 1, 0, 0)
        sizer_3_copy_1.Add(self.label_1_copy_1, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_3_copy_1.Add(self.labelTemperature, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(sizer_3_copy_1, 1, 0, 0)
        sizer_3_copy_2.Add(self.label_1_copy_2, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_3_copy_2.Add(self.labelPressure, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(sizer_3_copy_2, 1, 0, 0)
        sizer_1.Add(grid_sizer_1, 0, 0, 0)
        sizer_2.Add((20, 20), 1, 0, 0)
        sizer_2.Add(self.btnNext, 0, wx.ALL, 10)
        sizer_2.Add(self.btnCancel, 0, wx.ALL, 10)
        sizer_2.Add((20, 20), 1, 0, 0)
        sizer_1.Add(sizer_2, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()

    def OnNext(self, event):  # wxGlade: O2CalDlg.<event_handler>
        print "Event handler 'OnNext' not implemented!"
        event.Skip()

    def OnCancel(self, event):  # wxGlade: O2CalDlg.<event_handler>
        print "Event handler 'OnCancel' not implemented!"
        event.Skip()

# end of class O2CalDlg
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    O2CalDlg = O2CalDlg(None, wx.ID_ANY, "")
    app.SetTopWindow(O2CalDlg)
    O2CalDlg.Show()
    app.MainLoop()