#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Tue Sep 28 12:02:39 2010

import wx

# begin wxGlade: extracode
from Host.Common.GraphPanel import GraphPanel
from Host.Common.GraphPanel import GraphPanel
from Host.Common.GraphPanel import GraphPanel
from Host.Common.GraphPanel import GraphPanel

from Host.Common.GraphPanel import GraphPanel
from Host.Common.GraphPanel import GraphPanel

# end wxGlade



class SandboxGUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SandboxGUI.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_6 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_5 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_4 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "X Axis", style=wx.ALIGN_CENTRE)
        self.ListboxX = wx.ListBox(self.notebook_1_pane_1, -1, choices=[])
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "Y Axis")
        self.ListboxY = wx.ListBox(self.notebook_1_pane_1, -1, choices=[])
        self.ClearButton = wx.Button(self.notebook_1_pane_1, -1, "Clear")
        self.graphPanel1 = GraphPanel(self.notebook_1_pane_1, -1)
        self.EventLog = wx.TextCtrl(self.notebook_1_pane_2, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.HSCROLL|wx.TE_RICH2)
        self.Analyser1Label = wx.StaticText(self.notebook_1_pane_3, -1, "Chart1", style=wx.ALIGN_CENTRE)
        self.Chart1LB = wx.ListBox(self.notebook_1_pane_3, -1, choices=[], style=wx.LB_SINGLE|wx.LB_HSCROLL)
        self.Analyser2Label = wx.StaticText(self.notebook_1_pane_3, -1, "Chart2")
        self.Chart2LB = wx.ListBox(self.notebook_1_pane_3, -1, choices=[], style=wx.LB_SINGLE|wx.LB_HSCROLL)
        self.ClearAnalyzebutton = wx.Button(self.notebook_1_pane_3, -1, "Clear")
        self.analyzeGraph1 = GraphPanel(self.notebook_1_pane_3, -1)
        self.analyzeGraph2 = GraphPanel(self.notebook_1_pane_3, -1)
        self.SensorLabel1 = wx.StaticText(self.notebook_1_pane_4, -1, "Chart1")
        self.SensorLB1 = wx.ListBox(self.notebook_1_pane_4, -1, choices=[])
        self.SensorLabel2 = wx.StaticText(self.notebook_1_pane_4, -1, "Chart2")
        self.SensorLB2 = wx.ListBox(self.notebook_1_pane_4, -1, choices=[])
        self.SensorClearButton = wx.Button(self.notebook_1_pane_4, -1, "Clear")
        self.SensorChart1 = GraphPanel(self.notebook_1_pane_4, -1)
        self.SensorChart2 = GraphPanel(self.notebook_1_pane_4, -1)
        self.DriverRdSchemeButton = wx.Button(self.notebook_1_pane_5, -1, "Read Scheme")
        self.DriverAllVersionsButton = wx.Button(self.notebook_1_pane_5, -1, "All Versions")
        self.DriverDasGetTicksButton = wx.Button(self.notebook_1_pane_5, -1, "Das Get Ticks")
        self.DriverGetConfigFileButton = wx.Button(self.notebook_1_pane_5, -1, "Get Config File")
        self.DriverGetLockStatusButton = wx.Button(self.notebook_1_pane_5, -1, "Get Lock Status")
        self.DriverGetPressureReadingButton = wx.Button(self.notebook_1_pane_5, -1, "Get Pressure Reading")
        self.DriverGetValveMaskButton = wx.Button(self.notebook_1_pane_5, -1, "Get Valve Mask")
        self.DriverGetHostTicksButton = wx.Button(self.notebook_1_pane_5, -1, "Get Host Ticks")
        self.DriverLoadIniFileButton = wx.Button(self.notebook_1_pane_5, -1, "Load INI File")
        self.DriverReadSchemeSequenceButton = wx.Button(self.notebook_1_pane_5, -1, "Rd Scheme Seq")
        self.DriverStopScanButton = wx.Button(self.notebook_1_pane_5, -1, "Stop Scan")
        self.DriverResynchDASButton = wx.Button(self.notebook_1_pane_5, -1, "Resynch DAS")
        self.DriverStartEngineButton = wx.Button(self.notebook_1_pane_5, -1, "Start Engine")
        self.DriverStartScanButton = wx.Button(self.notebook_1_pane_5, -1, "Start Scan")
        self.DriverRdDASRegButton = wx.Button(self.notebook_1_pane_5, -1, "Read DAS Reg")
        self.DriverWrtDASRegButton = wx.Button(self.notebook_1_pane_5, -1, "Write DAS Reg")
        self.DriverHostRdyButton = wx.Button(self.notebook_1_pane_5, -1, "Host Ready")
        self.DriverRdValveSeqButton = wx.Button(self.notebook_1_pane_5, -1, "Read Valve Seq")
        self.label_5 = wx.StaticText(self.notebook_1_pane_5, -1, "Register:")
        self.DriverRegisterTextCtrl = wx.TextCtrl(self.notebook_1_pane_5, -1, "")
        self.label_6 = wx.StaticText(self.notebook_1_pane_5, -1, "     Value:")
        self.DriverRegValueTextCtrl = wx.TextCtrl(self.notebook_1_pane_5, -1, "")
        self.DriverTextCtrl = wx.TextCtrl(self.notebook_1_pane_5, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.HSCROLL|wx.TE_RICH2|wx.TE_LINEWRAP|wx.TE_WORDWRAP)
        self.DriverRegisterListBox = wx.ListBox(self.notebook_1_pane_5, -1, choices=[], style=wx.LB_SINGLE|wx.LB_HSCROLL)
        self.HD5Viewerbutton = wx.Button(self.notebook_1_pane_6, -1, "HD5Viewer")
        self.StartFlowbutton = wx.Button(self.notebook_1_pane_6, -1, "StartFlow")
        self.WLMPkScrnbutton = wx.Button(self.notebook_1_pane_6, -1, "WLMPkScrn")
        self.SchemeBuildbutton = wx.Button(self.notebook_1_pane_6, -1, "SchemeBuild")
        self.CalibrateSystemTestButton = wx.Button(self.notebook_1_pane_6, -1, "SystemCal")
        self.ViewSystemCalButton = wx.Button(self.notebook_1_pane_6, -1, "ViewSysCal")
        self.SetFitParmsbutton = wx.Button(self.notebook_1_pane_6, -1, "SetFitParms")
        self.ThresStatsbutton = wx.Button(self.notebook_1_pane_6, -1, "ThresStats")
        self.ViewTStatsbutton = wx.Button(self.notebook_1_pane_6, -1, "ViewTStats")
        self.FSRSquishbutton = wx.Button(self.notebook_1_pane_6, -1, "FSRSquish")
        self.Set20Kbutton = wx.Button(self.notebook_1_pane_6, -1, "Set20K")
        self.WLM_ETA_ThermTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.WLM_WBHSK_ThermTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.WLM_OpticalSwitchTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.WLM_EEPROMTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.WLMECETA1Testbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.WLMEC_ETA2Testbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.WLMEC_REF1Testbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.WLMEC_REF2Testbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PB_HBTECbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PB_WBTECbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PB_Htrbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PB_ProportionalValveTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PB_ProportionalValve2Testbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PB_SolenoidValveTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PB_PZTWaveformTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PS_U2 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PS_U3 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PS_U6 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.PS_U7 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.SOA_Therm = wx.Button(self.notebook_1_pane_6, -1, "")
        self.SOA_Current = wx.Button(self.notebook_1_pane_6, -1, "")
        self.SOA_TEC = wx.Button(self.notebook_1_pane_6, -1, "")
        self.LB_SelfTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.LB_EEPROMTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.LB_RDAtoDTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.LB_FPGADIGIOTestbutton = wx.Button(self.notebook_1_pane_6, -1, "")
        self.LB_Laser1 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.LB_Laser2 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.LB_Laser3 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.LB_Laser4 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_39 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_40 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_41 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_42 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_43 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_44 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_45 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_46 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_47 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_48 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_49 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_50 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.button_51 = wx.Button(self.notebook_1_pane_6, -1, "")
        self.label_3 = wx.StaticText(self.notebook_1_pane_6, -1, ".")
        self.Commenttext_ctrl = wx.TextCtrl(self.notebook_1_pane_6, -1, "")
        self.TestResulttext_ctrl = wx.TextCtrl(self.notebook_1_pane_6, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_RICH)
        self.TestGraph1Title = wx.StaticText(self.notebook_1_pane_6, -1, "")
        self.TestGraph1 = GraphPanel(self.notebook_1_pane_6, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX, self.OnListBoxXSelected, self.ListboxX)
        self.Bind(wx.EVT_LISTBOX, self.OnListBoxYSelected, self.ListboxY)
        self.Bind(wx.EVT_BUTTON, self.OnClear, self.ClearButton)
        self.Bind(wx.EVT_LISTBOX, self.OnChart1LB, self.Chart1LB)
        self.Bind(wx.EVT_LISTBOX, self.OnChart2LB, self.Chart2LB)
        self.Bind(wx.EVT_BUTTON, self.OnClearAnalzeButton, self.ClearAnalyzebutton)
        self.Bind(wx.EVT_LISTBOX, self.OnSensorLB1, self.SensorLB1)
        self.Bind(wx.EVT_LISTBOX, self.OnSensorLB2, self.SensorLB2)
        self.Bind(wx.EVT_BUTTON, self.OnSensorClearButton, self.SensorClearButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverRdSchemeButton, self.DriverRdSchemeButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverAllVersionsButton, self.DriverAllVersionsButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverDASGetTicksButton, self.DriverDasGetTicksButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverGetConfigFileButton, self.DriverGetConfigFileButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverGetLockStatusButton, self.DriverGetLockStatusButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverGetPressureReadingButton, self.DriverGetPressureReadingButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverGetValveMaskButton, self.DriverGetValveMaskButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverGetHostTicksButton, self.DriverGetHostTicksButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverLoadINIFileButton, self.DriverLoadIniFileButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverReadSchemeSequenceButton, self.DriverReadSchemeSequenceButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverStopScanButton, self.DriverStopScanButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverResynchDASButton, self.DriverResynchDASButton)
        self.Bind(wx.EVT_BUTTON, self.OnStartEngineButton, self.DriverStartEngineButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverStartScan, self.DriverStartScanButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverRdDASRegButton, self.DriverRdDASRegButton)
        self.Bind(wx.EVT_BUTTON, self.OnWrtDASRegButton, self.DriverWrtDASRegButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverHostReadyButton, self.DriverHostRdyButton)
        self.Bind(wx.EVT_BUTTON, self.OnDriverRdValveSeqButton, self.DriverRdValveSeqButton)
        self.Bind(wx.EVT_LISTBOX, self.OnDriverRegisterListBox, self.DriverRegisterListBox)
        self.Bind(wx.EVT_BUTTON, self.OnHD5Viewerbutton, self.HD5Viewerbutton)
        self.Bind(wx.EVT_BUTTON, self.OnStartFlowbutton, self.StartFlowbutton)
        self.Bind(wx.EVT_BUTTON, self.OnWLMPkScrnbutton, self.WLMPkScrnbutton)
        self.Bind(wx.EVT_BUTTON, self.OnSchemeBuildbutton, self.SchemeBuildbutton)
        self.Bind(wx.EVT_BUTTON, self.OnCalibrateSystemButton, self.CalibrateSystemTestButton)
        self.Bind(wx.EVT_BUTTON, self.OnViewSystemCalButton, self.ViewSystemCalButton)
        self.Bind(wx.EVT_BUTTON, self.OnSetFitParmsbutton, self.SetFitParmsbutton)
        self.Bind(wx.EVT_BUTTON, self.OnThresStatsbutton, self.ThresStatsbutton)
        self.Bind(wx.EVT_BUTTON, self.OnViewTStatsbutton, self.ViewTStatsbutton)
        self.Bind(wx.EVT_BUTTON, self.OnFSRSquishbutton, self.FSRSquishbutton)
        self.Bind(wx.EVT_BUTTON, self.OnSet20Kbutton, self.Set20Kbutton)
        self.Bind(wx.EVT_BUTTON, self.OnWLM_ETA_ThermTestbutton, self.WLM_ETA_ThermTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnWLM_WBHSK_ThermTestbutton, self.WLM_WBHSK_ThermTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnWLM_OpticalSwitchTestbutton, self.WLM_OpticalSwitchTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnWLM_EEPROMTestbutton, self.WLM_EEPROMTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnWLMECETA1Testbutton, self.WLMECETA1Testbutton)
        self.Bind(wx.EVT_BUTTON, self.OnWLMEC_ETA2Testbutton, self.WLMEC_ETA2Testbutton)
        self.Bind(wx.EVT_BUTTON, self.OnWLMEC_REF1Testbutton, self.WLMEC_REF1Testbutton)
        self.Bind(wx.EVT_BUTTON, self.OnWLMEC_REF2Testbutton, self.WLMEC_REF2Testbutton)
        self.Bind(wx.EVT_BUTTON, self.OnPB_HBTECbutton, self.PB_HBTECbutton)
        self.Bind(wx.EVT_BUTTON, self.OnPB_WBTECbutton, self.PB_WBTECbutton)
        self.Bind(wx.EVT_BUTTON, self.OnPB_Htrbutton, self.PB_Htrbutton)
        self.Bind(wx.EVT_BUTTON, self.OnPB_ProportionalValveTestbutton, self.PB_ProportionalValveTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnPB_ProportionalValve2Testbutton, self.PB_ProportionalValve2Testbutton)
        self.Bind(wx.EVT_BUTTON, self.OnPB_SolenoidValveTestbutton, self.PB_SolenoidValveTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnPB_PZTWaveformTestbutton, self.PB_PZTWaveformTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnPS_U2, self.PS_U2)
        self.Bind(wx.EVT_BUTTON, self.OnPS_U3, self.PS_U3)
        self.Bind(wx.EVT_BUTTON, self.OnPS_U6, self.PS_U6)
        self.Bind(wx.EVT_BUTTON, self.OnPS_U7, self.PS_U7)
        self.Bind(wx.EVT_BUTTON, self.OnSOA_Therm, self.SOA_Therm)
        self.Bind(wx.EVT_BUTTON, self.OnSOA_Current, self.SOA_Current)
        self.Bind(wx.EVT_BUTTON, self.OnSOA_TEC, self.SOA_TEC)
        self.Bind(wx.EVT_BUTTON, self.OnLB_SelfTestbutton, self.LB_SelfTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnLB_EEPROMTestbutton, self.LB_EEPROMTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnLB_RDAtoDTestbutton, self.LB_RDAtoDTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnLB_FPGA_DIGIOTestbutton, self.LB_FPGADIGIOTestbutton)
        self.Bind(wx.EVT_BUTTON, self.OnLB_Laser1, self.LB_Laser1)
        self.Bind(wx.EVT_BUTTON, self.OnLB_Laser2, self.LB_Laser2)
        self.Bind(wx.EVT_BUTTON, self.OnLB_Laser3, self.LB_Laser3)
        self.Bind(wx.EVT_BUTTON, self.OnLB_Laser4, self.LB_Laser4)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SandboxGUI.__set_properties
        self.SetTitle("Config Utils...")
        self.SetSize((600, 600))
        self.ListboxX.SetMinSize((140,155))
        self.ListboxY.SetMinSize((140, 150))
        self.graphPanel1.SetMinSize((400,300))
        self.notebook_1_pane_2.SetMinSize((584, 535))
        self.Analyser1Label.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.Analyser2Label.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.SensorLabel1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.SensorLabel2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.DriverRdSchemeButton.SetMinSize((116, 23))
        self.DriverAllVersionsButton.SetMinSize((116, 23))
        self.DriverDasGetTicksButton.SetMinSize((116, 23))
        self.DriverGetConfigFileButton.SetMinSize((116, 23))
        self.DriverGetLockStatusButton.SetMinSize((116, 23))
        self.DriverGetPressureReadingButton.SetMinSize((116, 23))
        self.DriverGetValveMaskButton.SetMinSize((116, 23))
        self.DriverGetHostTicksButton.SetMinSize((116, 23))
        self.DriverLoadIniFileButton.SetMinSize((116, 23))
        self.DriverReadSchemeSequenceButton.SetMinSize((116, 23))
        self.DriverStopScanButton.SetMinSize((116, 23))
        self.DriverResynchDASButton.SetMinSize((116, 23))
        self.DriverStartEngineButton.SetMinSize((116, 23))
        self.DriverStartScanButton.SetMinSize((116, 23))
        self.DriverRdDASRegButton.SetMinSize((116, 23))
        self.DriverWrtDASRegButton.SetMinSize((116, 23))
        self.DriverHostRdyButton.SetMinSize((116, 23))
        self.DriverRdValveSeqButton.SetMinSize((116, 23))
        self.label_5.SetMinSize((45, 13))
        self.DriverRegisterTextCtrl.SetMinSize((200, 20))
        self.label_6.SetMinSize((45, 13))
        self.DriverRegValueTextCtrl.SetMinSize((200, 20))
        self.WLMPkScrnbutton.Enable(False)
        self.TestGraph1.Hide()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SandboxGUI.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.GridSizer(20, 3, 0, 0)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(6, 3, 0, 0)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.label_1, 0, wx.TOP|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_3.Add(self.ListboxX, 1, wx.EXPAND, 0)
        sizer_3.Add(self.label_2, 0, wx.TOP|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_3.Add(self.ListboxY, 1, wx.EXPAND, 0)
        sizer_3.Add(self.ClearButton, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 6)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_2.Add(self.graphPanel1, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_2)
        sizer_4.Add(self.EventLog, 1, wx.ALL|wx.EXPAND, 6)
        self.notebook_1_pane_2.SetSizer(sizer_4)
        sizer_6.Add(self.Analyser1Label, 0, wx.ALL, 10)
        sizer_6.Add(self.Chart1LB, 1, wx.LEFT|wx.RIGHT, 6)
        sizer_6.Add((20, 20), 0, 0, 0)
        sizer_6.Add(self.Analyser2Label, 0, wx.ALL, 10)
        sizer_6.Add(self.Chart2LB, 1, wx.LEFT|wx.RIGHT, 6)
        sizer_6.Add(self.ClearAnalyzebutton, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 6)
        sizer_5.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_7.Add(self.analyzeGraph1, 1, wx.EXPAND, 0)
        sizer_7.Add(self.analyzeGraph2, 1, wx.EXPAND, 0)
        sizer_5.Add(sizer_7, 1, wx.EXPAND, 0)
        self.notebook_1_pane_3.SetSizer(sizer_5)
        sizer_9.Add(self.SensorLabel1, 0, wx.ALL, 10)
        sizer_9.Add(self.SensorLB1, 1, 0, 0)
        sizer_9.Add(self.SensorLabel2, 0, wx.ALL, 10)
        sizer_9.Add(self.SensorLB2, 1, 0, 0)
        sizer_9.Add(self.SensorClearButton, 0, wx.TOP|wx.BOTTOM, 6)
        sizer_8.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_10.Add(self.SensorChart1, 1, wx.EXPAND, 0)
        sizer_10.Add(self.SensorChart2, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_10, 1, wx.EXPAND, 0)
        self.notebook_1_pane_4.SetSizer(sizer_8)
        grid_sizer_1.Add(self.DriverRdSchemeButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverAllVersionsButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverDasGetTicksButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverGetConfigFileButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverGetLockStatusButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverGetPressureReadingButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverGetValveMaskButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverGetHostTicksButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverLoadIniFileButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverReadSchemeSequenceButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverStopScanButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverResynchDASButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverStartEngineButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverStartScanButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverRdDASRegButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverWrtDASRegButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverHostRdyButton, 0, 0, 0)
        grid_sizer_1.Add(self.DriverRdValveSeqButton, 0, 0, 0)
        sizer_12.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        sizer_13.Add(self.label_5, 0, wx.ALL, 0)
        sizer_13.Add(self.DriverRegisterTextCtrl, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_13, 0, 0, 0)
        sizer_14.Add(self.label_6, 0, 0, 0)
        sizer_14.Add(self.DriverRegValueTextCtrl, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_14, 0, 0, 0)
        sizer_12.Add(self.DriverTextCtrl, 1, wx.EXPAND, 0)
        sizer_11.Add(sizer_12, 2, wx.EXPAND, 0)
        sizer_11.Add(self.DriverRegisterListBox, 1, wx.EXPAND, 0)
        self.notebook_1_pane_5.SetSizer(sizer_11)
        grid_sizer_2.Add(self.HD5Viewerbutton, 0, 0, 0)
        grid_sizer_2.Add(self.StartFlowbutton, 0, 0, 0)
        grid_sizer_2.Add(self.WLMPkScrnbutton, 0, 0, 0)
        grid_sizer_2.Add(self.SchemeBuildbutton, 0, 0, 0)
        grid_sizer_2.Add(self.CalibrateSystemTestButton, 0, 0, 0)
        grid_sizer_2.Add(self.ViewSystemCalButton, 0, 0, 0)
        grid_sizer_2.Add(self.SetFitParmsbutton, 0, 0, 0)
        grid_sizer_2.Add(self.ThresStatsbutton, 0, 0, 0)
        grid_sizer_2.Add(self.ViewTStatsbutton, 0, 0, 0)
        grid_sizer_2.Add(self.FSRSquishbutton, 0, 0, 0)
        grid_sizer_2.Add(self.Set20Kbutton, 0, 0, 0)
        grid_sizer_2.Add(self.WLM_ETA_ThermTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.WLM_WBHSK_ThermTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.WLM_OpticalSwitchTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.WLM_EEPROMTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.WLMECETA1Testbutton, 0, 0, 0)
        grid_sizer_2.Add(self.WLMEC_ETA2Testbutton, 0, 0, 0)
        grid_sizer_2.Add(self.WLMEC_REF1Testbutton, 0, 0, 0)
        grid_sizer_2.Add(self.WLMEC_REF2Testbutton, 0, 0, 0)
        grid_sizer_2.Add(self.PB_HBTECbutton, 0, 0, 0)
        grid_sizer_2.Add(self.PB_WBTECbutton, 0, 0, 0)
        grid_sizer_2.Add(self.PB_Htrbutton, 0, 0, 0)
        grid_sizer_2.Add(self.PB_ProportionalValveTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.PB_ProportionalValve2Testbutton, 0, 0, 0)
        grid_sizer_2.Add(self.PB_SolenoidValveTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.PB_PZTWaveformTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.PS_U2, 0, 0, 0)
        grid_sizer_2.Add(self.PS_U3, 0, 0, 0)
        grid_sizer_2.Add(self.PS_U6, 0, 0, 0)
        grid_sizer_2.Add(self.PS_U7, 0, 0, 0)
        grid_sizer_2.Add(self.SOA_Therm, 0, 0, 0)
        grid_sizer_2.Add(self.SOA_Current, 0, 0, 0)
        grid_sizer_2.Add(self.SOA_TEC, 0, 0, 0)
        grid_sizer_2.Add(self.LB_SelfTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.LB_EEPROMTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.LB_RDAtoDTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.LB_FPGADIGIOTestbutton, 0, 0, 0)
        grid_sizer_2.Add(self.LB_Laser1, 0, 0, 0)
        grid_sizer_2.Add(self.LB_Laser2, 0, 0, 0)
        grid_sizer_2.Add(self.LB_Laser3, 0, 0, 0)
        grid_sizer_2.Add(self.LB_Laser4, 0, 0, 0)
        grid_sizer_2.Add(self.button_39, 0, 0, 0)
        grid_sizer_2.Add(self.button_40, 0, 0, 0)
        grid_sizer_2.Add(self.button_41, 0, 0, 0)
        grid_sizer_2.Add(self.button_42, 0, 0, 0)
        grid_sizer_2.Add(self.button_43, 0, 0, 0)
        grid_sizer_2.Add(self.button_44, 0, 0, 0)
        grid_sizer_2.Add(self.button_45, 0, 0, 0)
        grid_sizer_2.Add(self.button_46, 0, 0, 0)
        grid_sizer_2.Add(self.button_47, 0, 0, 0)
        grid_sizer_2.Add(self.button_48, 0, 0, 0)
        grid_sizer_2.Add(self.button_49, 0, 0, 0)
        grid_sizer_2.Add(self.button_50, 0, 0, 0)
        grid_sizer_2.Add(self.button_51, 0, 0, 0)
        sizer_16.Add(grid_sizer_2, 0, 0, 0)
        sizer_19.Add(self.label_3, 0, wx.LEFT|wx.RIGHT, 5)
        sizer_19.Add(self.Commenttext_ctrl, 1, wx.EXPAND, 0)
        sizer_18.Add(sizer_19, 1, wx.EXPAND, 0)
        sizer_18.Add(self.TestResulttext_ctrl, 25, wx.ALL|wx.EXPAND, 3)
        sizer_16.Add(sizer_18, 1, wx.EXPAND, 0)
        sizer_17.Add(self.TestGraph1Title, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_17.Add(self.TestGraph1, 3, wx.EXPAND, 0)
        sizer_16.Add(sizer_17, 0, wx.EXPAND, 0)
        sizer_15.Add(sizer_16, 1, wx.EXPAND, 0)
        self.notebook_1_pane_6.SetSizer(sizer_15)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Ringdowns")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Events")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "Analyze")
        self.notebook_1.AddPage(self.notebook_1_pane_4, "Sensors")
        self.notebook_1.AddPage(self.notebook_1_pane_5, "Driver")
        self.notebook_1.AddPage(self.notebook_1_pane_6, "Config")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnListBoxXSelected(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnListBoxXSelected' not implemented!"
        event.Skip()

    def OnListBoxYSelected(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnListBoxYSelected' not implemented!"
        event.Skip()

    def OnClear(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnClear' not implemented!"
        event.Skip()

    def OnChart1LB(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnChart1LB' not implemented!"
        event.Skip()

    def OnChart2LB(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnChart2LB' not implemented!"
        event.Skip()

    def OnClearAnalzeButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnClearAnalzeButton' not implemented!"
        event.Skip()

    def OnSensorLB1(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnSensorLB1' not implemented!"
        event.Skip()

    def OnSensorLB2(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnSensorLB2' not implemented!"
        event.Skip()

    def OnSensorClearButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnSensorClearButton' not implemented!"
        event.Skip()

    def OnDriverRdSchemeButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverRdSchemeButton' not implemented!"
        event.Skip()

    def OnDriverAllVersionsButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverAllVersionsButton' not implemented!"
        event.Skip()

    def OnDriverDASGetTicksButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverDASGetTicksButton' not implemented!"
        event.Skip()

    def OnDriverGetConfigFileButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverGetConfigFileButton' not implemented!"
        event.Skip()

    def OnDriverGetLockStatusButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverGetLockStatusButton' not implemented!"
        event.Skip()

    def OnDriverGetPressureReadingButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverGetPressureReadingButton' not implemented!"
        event.Skip()

    def OnDriverGetValveMaskButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverGetValveMaskButton' not implemented!"
        event.Skip()

    def OnDriverGetHostTicksButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverGetHostTicksButton' not implemented!"
        event.Skip()

    def OnDriverLoadINIFileButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverLoadINIFileButton' not implemented!"
        event.Skip()

    def OnDriverReadSchemeSequenceButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverReadSchemeSequenceButton' not implemented!"
        event.Skip()

    def OnDriverStopScanButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverStopScanButton' not implemented!"
        event.Skip()

    def OnDriverResynchDASButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverResynchDASButton' not implemented!"
        event.Skip()

    def OnStartEngineButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnStartEngineButton' not implemented!"
        event.Skip()

    def OnDriverStartScan(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverStartScan' not implemented!"
        event.Skip()

    def OnDriverRdDASRegButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverRdDASRegButton' not implemented!"
        event.Skip()

    def OnWrtDASRegButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWrtDASRegButton' not implemented!"
        event.Skip()

    def OnDriverHostReadyButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverHostReadyButton' not implemented!"
        event.Skip()

    def OnDriverRdValveSeqButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverRdValveSeqButton' not implemented!"
        event.Skip()

    def OnDriverRegisterListBox(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnDriverRegisterListBox' not implemented!"
        event.Skip()

    def OnHD5Viewerbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnHD5Viewerbutton' not implemented!"
        event.Skip()

    def OnStartFlowbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnStartFlowbutton' not implemented!"
        event.Skip()

    def OnWLMPkScrnbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWLMPkScrnbutton' not implemented!"
        event.Skip()

    def OnSchemeBuildbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnSchemeBuildbutton' not implemented!"
        event.Skip()

    def OnCalibrateSystemButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnCalibrateSystemButton' not implemented!"
        event.Skip()

    def OnViewSystemCalButton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnViewSystemCalButton' not implemented!"
        event.Skip()

    def OnSetFitParmsbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnSetFitParmsbutton' not implemented!"
        event.Skip()

    def OnThresStatsbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnThresStatsbutton' not implemented!"
        event.Skip()

    def OnViewTStatsbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnViewTStatsbutton' not implemented!"
        event.Skip()

    def OnFSRSquishbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnFSRSquishbutton' not implemented!"
        event.Skip()

    def OnSet20Kbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnSet20Kbutton' not implemented!"
        event.Skip()

    def OnWLM_ETA_ThermTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWLM_ETA_ThermTestbutton' not implemented!"
        event.Skip()

    def OnWLM_WBHSK_ThermTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWLM_WBHSK_ThermTestbutton' not implemented!"
        event.Skip()

    def OnWLM_OpticalSwitchTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWLM_OpticalSwitchTestbutton' not implemented!"
        event.Skip()

    def OnWLM_EEPROMTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWLM_EEPROMTestbutton' not implemented!"
        event.Skip()

    def OnWLMECETA1Testbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWLMECETA1Testbutton' not implemented!"
        event.Skip()

    def OnWLMEC_ETA2Testbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWLMEC_ETA2Testbutton' not implemented!"
        event.Skip()

    def OnWLMEC_REF1Testbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWLMEC_REF1Testbutton' not implemented!"
        event.Skip()

    def OnWLMEC_REF2Testbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnWLMEC_REF2Testbutton' not implemented!"
        event.Skip()

    def OnPB_HBTECbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPB_HBTECbutton' not implemented!"
        event.Skip()

    def OnPB_WBTECbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPB_WBTECbutton' not implemented!"
        event.Skip()

    def OnPB_Htrbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPB_Htrbutton' not implemented!"
        event.Skip()

    def OnPB_ProportionalValveTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPB_ProportionalValveTestbutton' not implemented!"
        event.Skip()

    def OnPB_ProportionalValve2Testbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPB_ProportionalValve2Testbutton' not implemented!"
        event.Skip()

    def OnPB_SolenoidValveTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPB_SolenoidValveTestbutton' not implemented!"
        event.Skip()

    def OnPB_PZTWaveformTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPB_PZTWaveformTestbutton' not implemented!"
        event.Skip()

    def OnPS_U2(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPS_U2' not implemented!"
        event.Skip()

    def OnPS_U3(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPS_U3' not implemented!"
        event.Skip()

    def OnPS_U6(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPS_U6' not implemented!"
        event.Skip()

    def OnPS_U7(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnPS_U7' not implemented!"
        event.Skip()

    def OnSOA_Therm(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnSOA_Therm' not implemented!"
        event.Skip()

    def OnSOA_Current(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnSOA_Current' not implemented!"
        event.Skip()

    def OnSOA_TEC(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnSOA_TEC' not implemented!"
        event.Skip()

    def OnLB_SelfTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnLB_SelfTestbutton' not implemented!"
        event.Skip()

    def OnLB_EEPROMTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnLB_EEPROMTestbutton' not implemented!"
        event.Skip()

    def OnLB_RDAtoDTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnLB_RDAtoDTestbutton' not implemented!"
        event.Skip()

    def OnLB_FPGA_DIGIOTestbutton(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnLB_FPGA_DIGIOTestbutton' not implemented!"
        event.Skip()

    def OnLB_Laser1(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnLB_Laser1' not implemented!"
        event.Skip()

    def OnLB_Laser2(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnLB_Laser2' not implemented!"
        event.Skip()

    def OnLB_Laser3(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnLB_Laser3' not implemented!"
        event.Skip()

    def OnLB_Laser4(self, event): # wxGlade: SandboxGUI.<event_handler>
        print "Event handler `OnLB_Laser4' not implemented!"
        event.Skip()

# end of class SandboxGUI


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = SandboxGUI(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
