/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT dspMain.cdb */

/*  Include Header Files  */
#include <std.h>
#include <prd.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far PRD_Obj PRD_scheduler;
extern far PRD_Obj PRD_sentryHandler;
extern far PRD_Obj PRD_timeStamp;
extern far HST_Obj RTA_fromHost;
extern far HST_Obj RTA_toHost;
extern far SWI_Obj PRD_swi;
extern far SWI_Obj KNL_swi;
extern far TSK_Obj TSK_idle;
extern far TSK_Obj TSK_scheduler;
extern far TSK_Obj TSK_rdFitting;
extern far TSK_Obj TSK_rdDataMoving;
extern far TSK_Obj TSK_spectCntrl;
extern far TSK_Obj TSK_sentryHandler;
extern far LOG_Obj LOG_system;
extern far LOG_Obj trace;
extern far SEM_Obj SEM_scheduler;
extern far SEM_Obj SEM_rdFitting;
extern far SEM_Obj SEM_rdDataMoving;
extern far SEM_Obj SEM_rdBuffer0Available;
extern far SEM_Obj SEM_rdBuffer1Available;
extern far SEM_Obj SEM_startRdCycle;
extern far SEM_Obj SEM_waitForRdMan;
extern far SEM_Obj SEM_sentryHandler;
extern far SEM_Obj SEM_hpiIntBackend;
extern far STS_Obj IDL_busyObj;


#ifdef __cplusplus
}
#endif /* extern "C" */
