#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Fri Feb 04 18:53:30 2011

import wx

# begin wxGlade: extracode
from Host.Common.GraphPanel import GraphPanel

# end wxGlade



class ModeViewGUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ModeViewGUI.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.graph_panel_1 = GraphPanel(self, -1)
        self.panel_2 = wx.Panel(self, -1)
        self.panel_filler1_1 = wx.Panel(self.panel_2, -1)
        self.panel_filler2_1 = wx.Panel(self.panel_2, -1)
        self.label_autoscale1 = wx.StaticText(self.panel_2, -1, "Autoscale")
        self.checkbox_autoscale_1 = wx.CheckBox(self.panel_2, -1, "")
        self.label_min_1 = wx.StaticText(self.panel_2, -1, "Min")
        self.text_ctrl_min_1 = wx.TextCtrl(self.panel_2, -1, "0", style=wx.TE_PROCESS_ENTER)
        self.label_max_1 = wx.StaticText(self.panel_2, -1, "Max")
        self.text_ctrl_max_1 = wx.TextCtrl(self.panel_2, -1, "50", style=wx.TE_PROCESS_ENTER)
        self.panel_control = wx.Panel(self, -1)
        self.button_clear = wx.Button(self.panel_control, wx.ID_CLEAR, "")
        self.button_connect = wx.Button(self.panel_control, -1, "Connect")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_CHECKBOX, self.onAutoscale1, self.checkbox_autoscale_1)
        self.Bind(wx.EVT_TEXT_ENTER, self.onMin1Enter, self.text_ctrl_min_1)
        self.Bind(wx.EVT_TEXT_ENTER, self.onMax1Enter, self.text_ctrl_max_1)
        self.Bind(wx.EVT_BUTTON, self.onClear, self.button_clear)
        self.Bind(wx.EVT_BUTTON, self.onConnect, self.button_connect)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ModeViewGUI.__set_properties
        self.SetTitle("Mode Viewer")
        self.SetSize((1280, 826))
        self.checkbox_autoscale_1.SetValue(1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ModeViewGUI.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_for_graphs = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_graph1 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_graph_panel_1 = wx.FlexGridSizer(3, 2, 10, 10)
        sizer_graph1.Add(self.graph_panel_1, 1, wx.EXPAND, 0)
        grid_sizer_graph_panel_1.Add(self.panel_filler1_1, 1, wx.EXPAND, 0)
        grid_sizer_graph_panel_1.Add(self.panel_filler2_1, 1, wx.EXPAND, 0)
        grid_sizer_graph_panel_1.Add(self.label_autoscale1, 0, wx.LEFT|wx.RIGHT, 10)
        grid_sizer_graph_panel_1.Add(self.checkbox_autoscale_1, 0, 0, 0)
        grid_sizer_graph_panel_1.Add(self.label_min_1, 0, wx.LEFT|wx.RIGHT, 10)
        grid_sizer_graph_panel_1.Add(self.text_ctrl_min_1, 0, wx.RIGHT|wx.EXPAND, 10)
        grid_sizer_graph_panel_1.Add(self.label_max_1, 0, wx.LEFT|wx.RIGHT, 10)
        grid_sizer_graph_panel_1.Add(self.text_ctrl_max_1, 0, wx.RIGHT|wx.EXPAND, 10)
        self.panel_2.SetSizer(grid_sizer_graph_panel_1)
        sizer_graph1.Add(self.panel_2, 0, wx.EXPAND, 0)
        sizer_for_graphs.Add(sizer_graph1, 1, wx.EXPAND, 0)
        sizer_3.Add(self.button_clear, 0, wx.ALL, 20)
        sizer_3.Add(self.button_connect, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_3.Add((20, 20), 1, wx.ALIGN_CENTER_VERTICAL, 0)
        self.panel_control.SetSizer(sizer_3)
        sizer_for_graphs.Add(self.panel_control, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_for_graphs, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def onAutoscale1(self, event): # wxGlade: ModeViewGUI.<event_handler>
        print "Event handler `onAutoscale1' not implemented!"
        event.Skip()

    def onMin1Enter(self, event): # wxGlade: ModeViewGUI.<event_handler>
        print "Event handler `onMin1Enter' not implemented!"
        event.Skip()

    def onMax1Enter(self, event): # wxGlade: ModeViewGUI.<event_handler>
        print "Event handler `onMax1Enter' not implemented!"
        event.Skip()

    def onClear(self, event): # wxGlade: ModeViewGUI.<event_handler>
        print "Event handler `onClear' not implemented!"
        event.Skip()

    def onConnect(self, event): # wxGlade: ModeViewGUI.<event_handler>
        print "Event handler `onConnect' not implemented!"
        event.Skip()

# end of class ModeViewGUI


class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        modeViewGUI = ModeViewGUI(None, -1, "")
        self.SetTopWindow(modeViewGUI)
        modeViewGUI.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    ModeViewer = MyApp(0)
    ModeViewer.MainLoop()
