Configuration: # This is for high level information
  RpcTunnel:
    config_file: rpc_tunnel_configs.json
  Simulation:
    enabled: true
    ui_enabled: false
    random_ids: false
    analyzers:
      - ip_address: 192.168.10.101
        chassis: 4123
        analyzer: AMADS
        analyzer_num: 3001
        species:
          - NH3
          - HF
          - H2O
        source: analyze_AMADS_LCT
        mode: AMADS_LCT_mode
        interval: 1.1
        seed: 12345
        warmup_time: 90.0
      - ip_address: 192.168.10.102
        chassis: 4357
        analyzer: SBDS
        analyzer_num: 3002
        species:
          - HCl
          - H2O
        source: analyze_SADS
        mode: SBDS_mode
        interval: 1.2
        seed: 23456
        warmup_time: 90.0
      - ip_address: 192.168.10.103
        chassis: 4532
        analyzer: BFADS
        analyzer_num: 3003
        species:
          - H2S
          - HDO
        source: analyze_BFADS
        mode: BFADS_mode
        interval: 1.3
        seed: 34567
        warmup_time: 90.0
  Database:
    server: localhost
    port: 8086
    name: pigss_data
  HttpServer:
    listen_address: 0.0.0.0
    port: 8000

Settings:
  reference_mfc_flow: 40.0
  flow_settle_delay: 2.0
  madmapper_startup_delay: 30
  startup_plan: __default__  # Do NOT include extension or directory

Services:
  - Name: DBDecimator
    RPC_Port: 33052
    Parameters: # These are passed to the constructor
      db_name: pigss_data
      rpc_server_name: DBDecimator
      rpc_server_description: DBDecimator
      raw_filter_conditions:
        - ["valve_stable_time", ">", 15]
      start: true

Plugins:
  GrafanaLogger:
    sqlite:
      table_name: "Events"
      columns: ["rowid", "ClientTimestamp", "ClientName", "LogMessage", "Level"]
    limit: 20
    interval: 3
    timeout: 300
    retries: 1

  GrafanaDataGenerator:
    database:
      host: 0.0.0.0
      port: 8086
      database: "pigss_data"
      timeout: 300
      retries: 1
      measurements: "crds"
    server:
      user_keys: ["H2O", "CO2", "NH3", "CH4", "HF", "HCl", "O2"]
      data_dir: "/tmp"
      file_type: "csv"
