Configuration: # This is for high level information
  RpcTunnel:
    config_file: rpc_tunnel_configs.json
  Database:
    server: localhost
    port: 8086
    name: pigss_data
  HttpServer:
    listen_address: 0.0.0.0
    port: 8000

Settings:
  reference_mfc_flow: 40.0
  flow_settle_delay: 2.0
  madmapper_startup_delay: 30
  startup_plan: once_a_minute  # Do NOT include extension or directory

Services:
  - Name: DBDecimator
    RPC_Port: 33052
    Parameters: # These are passed to the constructor
      db_name: pigss_data
      rpc_server_name: DBDecimator
      rpc_server_description: DBDecimator
      raw_filter_conditions: 
        - ["valve_stable_time", ">", 15]
      start: true
