import os
from PyQt4.QtCore import *
from PyQt4.QtGui import *
import pyqtgraph as pg
from DateAxisItem import DateAxisItem

class H2O2ValidationFrame(QMainWindow):
    """
    Define user interface of H2O2Validation program
    """
    def __init__(self, parent=None):
        super(H2O2ValidationFrame, self).__init__(parent)
        self.setWindowTitle("H2O2 Validation")
        #self.setWindowState(Qt.WindowFullScreen)
        curr_dir = os.path.dirname(os.path.realpath(__file__))
        self.style_data = ""
        with open(os.path.join(curr_dir, 'styleSheet.qss'), 'r') as f:
            self.style_data = f.read()
        self.setStyleSheet(self.style_data)
        pg.setConfigOption('background', (64,64,64))
        self.create_widgets()
        self.set_connections()
        self.resize(1200,800)      
        
    def create_widgets(self):
        self.measurement_timer = QTimer()
        
        self.top_frame = QWidget()
        self.top_frame.setMaximumHeight(150)
        self.display_conc_ch4 = QLabel("0.00")
        self.display_conc_ch4.setAccessibleName("concentration")
        self.display_conc_ch4.setFrameShape(QFrame.Panel)
        self.display_conc_ch4.setFixedWidth(100)
        self.display_conc_h2o2 = QLabel("0.00")
        self.display_conc_h2o2.setAccessibleName("concentration")
        self.display_conc_h2o2.setFrameShape(QFrame.Panel)
        self.display_conc_h2o2.setFixedWidth(100)
        time_axis = DateAxisItem("bottom")
        time_series_plot = pg.PlotWidget(axisItems={'bottom':time_axis})
        time_series_plot.showGrid(x=True, y=True)
        time_series_plot.setLabels(left="CH4 (ppm)")
        self.ch4_plot = time_series_plot.plot(pen=pg.mkPen(color=(255,255,255), width=1))
        top_layout = QHBoxLayout()
        data_layout = QVBoxLayout()
        data_layout.addStretch(1)
        data_row1 = QHBoxLayout()
        data_row1.addWidget(QLabel("<font size=16>H<sub>2</sub>O<sub>2</sub></font>"))
        data_row1.addWidget(self.display_conc_h2o2)
        data_layout.addLayout(data_row1)
        data_layout.addStretch(1)
        data_row2 = QHBoxLayout()
        data_row2.addWidget(QLabel("<font size=16>CH<sub>4</sub></font>"))
        data_row2.addWidget(self.display_conc_ch4)
        data_layout.addLayout(data_row2)
        data_layout.addStretch(1)
        top_layout.addLayout(data_layout)
        top_layout.addWidget(time_series_plot)
        self.top_frame.setLayout(top_layout)
        
        self.wizard_frame = QWidget()
        self.display_caption = QLabel("")
        self.display_caption.setAccessibleName("caption")
        self.display_instruction = QLabel("")
        self.display_instruction.setAccessibleName("instruction")
        self.display_instruction.setFixedWidth(800)
        self.display_instruction.setFixedHeight(600)
        self.display_instruction.setWordWrap(True)
        self.input_nominal_concentration = QLineEdit()
        self.display_instruction2 = QLabel("Click Next to continue.")
        self.display_instruction2.setAccessibleName("instruction2")
        self.nominal_concentration = QWidget()
        self.nominal_concentration.hide()
        nominal_concentration_layout = QHBoxLayout()
        nominal_concentration_layout.addWidget(QLabel("<b>Nominal Concentration (ppm)</b>"))
        nominal_concentration_layout.addWidget(self.input_nominal_concentration)
        self.nominal_concentration.setLayout(nominal_concentration_layout)
        information_layout = QVBoxLayout()
        information_layout.addWidget(self.display_caption)
        information_layout.addWidget(self.display_instruction)
        information_layout.addWidget(self.display_instruction2)
        information_layout.addWidget(self.nominal_concentration)
        information_layout.addStretch(1)
                
        # control buttons
        self.button_next_step = QPushButton("Next")
        self.button_cancel_process = QPushButton("Cancel")
        button_layout = QHBoxLayout()
        button_layout.addStretch(1)
        button_layout.addWidget(self.button_next_step)
        button_layout.addWidget(self.button_cancel_process)
        
        wizard_layout = QGridLayout()
        wizard_layout.setColumnStretch(0,1)
        wizard_layout.setColumnStretch(2,1)
        wizard_layout.addLayout(information_layout,0,1,Qt.AlignHCenter)
        wizard_layout.addLayout(button_layout,1,1,Qt.AlignHCenter)
        self.wizard_frame.setLayout(wizard_layout)
        
        # report 
        self.report_frame = QWidget()
        self.report = QTextEdit()
        self.report.setFixedWidth(800)
        self.report.setFixedHeight(800)
        self.report.setReadOnly(True)
        self.button_save_report = QPushButton("Save Report")
        self.button_cancel_report = QPushButton("Cancel")
        
        control_layout = QHBoxLayout()
        control_layout.addStretch(1)
        control_layout.addWidget(self.button_save_report)
        control_layout.addWidget(self.button_cancel_report)
        control_layout.addStretch(1)
        report_layout = QGridLayout()
        report_layout.setColumnStretch(0,1)
        report_layout.setColumnStretch(2,1)
        report_layout.addWidget(self.report,0,1,Qt.AlignHCenter)
        report_layout.addLayout(control_layout,1,1,Qt.AlignHCenter)
        self.report_frame.setLayout(report_layout)
        
        # login
        self.login_frame = QWidget()
        self.input_user_name = QLineEdit()
        self.input_password = QLineEdit()
        self.input_password.setEchoMode(QLineEdit.Password)        
        self.button_user_login = QPushButton("Login")
        self.button_cancel_login = QPushButton("Cancel")
        self.label_login_info = QLabel("")
        login_input = QFormLayout()
        login_input.addRow("User Name", self.input_user_name)
        login_input.addRow("Password", self.input_password)
        login_buttons = QHBoxLayout()
        login_buttons.addWidget(self.button_user_login)
        login_buttons.addWidget(self.button_cancel_login)
        login_layout = QGridLayout()
        login_layout.setColumnStretch(0,1)
        login_layout.setColumnStretch(2,1)
        login_layout.setRowStretch(1,1)
        login_layout.addLayout(login_input,2,1,Qt.AlignHCenter)
        login_layout.addLayout(login_buttons,3,1,Qt.AlignHCenter)
        login_layout.addWidget(self.label_login_info,4,1,Qt.AlignHCenter)
        login_layout.setRowStretch(5,1)
        self.login_frame.setLayout(login_layout)
            
        main_layout = QVBoxLayout()
        main_layout.addWidget(self.top_frame)
        main_layout.addWidget(self.wizard_frame)
        main_layout.addWidget(self.report_frame)
        main_layout.addWidget(self.login_frame)
        main_layout.addStretch(1)        
        
        central_widget = QWidget()
        central_widget.setLayout(main_layout)
        self.setCentralWidget(central_widget)
        
        self.report_frame.hide()
        self.top_frame.hide()
        self.wizard_frame.hide()
        
    def set_connections(self):
        self.measurement_timer.timeout.connect(self.measurement)
        self.button_next_step.clicked.connect(self.next_step)
        self.button_cancel_process.clicked.connect(self.cancel_process)
        self.button_save_report.clicked.connect(self.save_report)
        self.input_password.returnPressed.connect(self.user_login)
        self.button_user_login.clicked.connect(self.user_login)
        self.button_cancel_login.clicked.connect(self.cancel_login)