import os
from PyQt4.QtCore import *
from PyQt4.QtGui import *
import pyqtgraph as pg
from DateAxisItem import DateAxisItem

class H2O2ValidationFrame(QMainWindow):
    """
    Define user interface of H2O2Validation program
    """
    def __init__(self, parent=None):
        super(H2O2ValidationFrame, self).__init__(parent)
        self.setWindowTitle("H2O2 Validation")
        #self.setWindowState(Qt.WindowFullScreen)
        self.curr_dir = os.path.dirname(os.path.realpath(__file__))
        self.style_data = ""
        with open(os.path.join(self.curr_dir, 'styleSheet.qss'), 'r') as f:
            self.style_data = f.read()
        self.setStyleSheet(self.style_data)
        pg.setConfigOption('background', (64,64,64))
        self.create_widgets()
        self.set_connections()
        self.resize(1200,800)      
        
    def create_widgets(self):
        self.measurement_timer = QTimer()
        
        self.top_frame = QWidget()
        self.top_frame.setMaximumHeight(150)
        self.display_conc_ch4 = QLabel("0.00")
        self.display_conc_ch4.setAccessibleName("concentration")
        self.display_conc_ch4.setFrameShape(QFrame.Panel)
        self.display_conc_ch4.setFixedWidth(100)
        self.display_conc_h2o2 = QLabel("0.00")
        self.display_conc_h2o2.setAccessibleName("concentration")
        self.display_conc_h2o2.setFrameShape(QFrame.Panel)
        self.display_conc_h2o2.setFixedWidth(100)
        self.display_conc_h2o = QLabel("0.00")
        self.display_conc_h2o.setAccessibleName("concentration")
        self.display_conc_h2o.setFrameShape(QFrame.Panel)
        self.display_conc_h2o.setFixedWidth(100)
        time_axis = DateAxisItem("bottom")
        time_series_plot = pg.PlotWidget(axisItems={'bottom':time_axis})
        time_series_plot.showGrid(x=True, y=True)
        time_series_plot.setLabels(left="CH4 (ppm)")
        self.ch4_plot = time_series_plot.plot(pen=pg.mkPen(color=(255,255,255), width=1))
        top_layout = QHBoxLayout()
        data_layout = QVBoxLayout()
        data_layout.addStretch(1)
        data_row1 = QHBoxLayout()
        data_row1.addWidget(QLabel("<font size=12>H<sub>2</sub>O<sub>2</sub></font>(ppb)"))
        data_row1.addWidget(self.display_conc_h2o2)
        data_layout.addLayout(data_row1)
        data_layout.addStretch(1)
        data_row2 = QHBoxLayout()
        data_row2.addWidget(QLabel("<font size=12>CH<sub>4</sub></font>(ppm)"))
        data_row2.addWidget(self.display_conc_ch4)
        data_layout.addLayout(data_row2)
        data_layout.addStretch(1)
        data_row3 = QHBoxLayout()
        data_row3.addWidget(QLabel("<font size=12>H<sub>2</sub>O</font>(%)"))
        data_row3.addWidget(self.display_conc_h2o)
        data_layout.addLayout(data_row3)
        data_layout.addStretch(1)
        top_layout.addLayout(data_layout)
        top_layout.addWidget(time_series_plot)
        self.top_frame.setLayout(top_layout)
        
        self.wizard_frame = QWidget()
        self.display_caption = QLabel("")
        self.display_caption.setAccessibleName("caption")
        self.display_instruction = QLabel("")
        self.display_instruction.setAccessibleName("instruction")
        self.display_instruction.setFixedWidth(800)
        self.display_instruction.setFixedHeight(600)
        self.display_instruction.setWordWrap(True)
        self.select_cylinder = QComboBox()
        self.button_edit_cylinder = QPushButton("Edit Cylinder")
        self.button_edit_cylinder.setStyleSheet("width: 120px")
        self.display_instruction2 = QLabel("Click Next to continue.")
        self.display_instruction2.setAccessibleName("instruction2")
        self.measurement_progress = QProgressBar(self)
        self.measurement_progress.setRange(0, 100)
        self.measurement_progress.hide()
        self.cylinder_selection = QWidget()
        self.cylinder_selection.hide()
        cylinder_selection_layout = QHBoxLayout()
        cylinder_selection_layout.addWidget(QLabel("<b>Select Cylinder</b>"))
        cylinder_selection_layout.addWidget(self.select_cylinder)
        cylinder_selection_layout.addStretch(1)
        cylinder_selection_layout.addWidget(self.button_edit_cylinder)
        self.cylinder_selection.setLayout(cylinder_selection_layout)
        information_layout = QVBoxLayout()
        information_layout.addWidget(self.display_caption)
        information_layout.addWidget(self.display_instruction)
        info_layout = QHBoxLayout()
        info_layout.addWidget(self.display_instruction2)
        info_layout.addWidget(self.measurement_progress)
        information_layout.addLayout(info_layout)
        information_layout.addWidget(self.cylinder_selection)
        information_layout.addStretch(1)
                
        # control buttons
        self.button_skip_step = QPushButton("Skip")
        self.button_skip_step.hide()
        self.button_next_step = QPushButton("Next")
        self.button_cancel_process = QPushButton("Cancel")
        button_layout = QHBoxLayout()
        button_layout.addStretch(1)
        button_layout.addWidget(self.button_skip_step)
        button_layout.addWidget(self.button_next_step)
        button_layout.addWidget(self.button_cancel_process)
        
        wizard_layout = QGridLayout()
        wizard_layout.setColumnStretch(0,1)
        wizard_layout.setColumnStretch(2,1)
        wizard_layout.addLayout(information_layout,0,1,Qt.AlignHCenter)
        wizard_layout.addLayout(button_layout,1,1,Qt.AlignHCenter)
        self.wizard_frame.setLayout(wizard_layout)
        
        # report 
        self.report_frame = QWidget()
        self.report = QTextEdit()
        self.report.setFixedWidth(800)
        self.report.setFixedHeight(800)
        self.report.setReadOnly(True)
        self.button_exit = QPushButton("Exit Program")
        self.button_exit.setStyleSheet("width: 100px")
        
        control_layout = QHBoxLayout()
        control_layout.addStretch(1)
        control_layout.addWidget(self.button_exit)
        control_layout.addStretch(1)
        report_layout = QGridLayout()
        report_layout.setColumnStretch(0,1)
        report_layout.setColumnStretch(2,1)
        report_layout.addWidget(self.report,0,1,Qt.AlignHCenter)
        report_layout.addLayout(control_layout,1,1,Qt.AlignHCenter)
        self.report_frame.setLayout(report_layout)
        
        # login
        self.login_frame = QWidget()
        self.label_login_message = QLabel("")
        self.input_user_name = QLineEdit()
        self.input_password = QLineEdit()
        self.input_password.setEchoMode(QLineEdit.Password)        
        self.button_user_login = QPushButton("Login")
        self.button_cancel_login = QPushButton("Cancel")
        self.label_login_info = QLabel("")
        login_input = QFormLayout()
        login_input.addRow("User Name", self.input_user_name)
        login_input.addRow("Password", self.input_password)
        login_hbox = QHBoxLayout()
        login_hbox.addStretch(1)
        login_hbox.addLayout(login_input)
        login_hbox.addStretch(1)
        login_buttons = QHBoxLayout()
        login_buttons.addWidget(self.button_user_login)
        login_buttons.addWidget(self.button_cancel_login)
        login_layout = QGridLayout()
        login_layout.setColumnStretch(0,1)
        login_layout.setColumnStretch(2,1)
        login_layout.setRowStretch(0,1)
        login_layout.addWidget(self.label_login_message,1,1,Qt.AlignHCenter)
        login_layout.addLayout(login_hbox,2,1,Qt.AlignHCenter)
        login_layout.addLayout(login_buttons,3,1,Qt.AlignHCenter)
        login_layout.addWidget(self.label_login_info,4,1,Qt.AlignHCenter)
        login_layout.setRowStretch(5,1)
        self.login_frame.setLayout(login_layout)

        # cylinder
        self.cylinder_frame = QWidget()
        self.table_cylinder_list = QTableWidget(0, 4)
        self.table_cylinder_list.setMinimumSize(QSize(600, 300))
        self.table_cylinder_list.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table_cylinder_list.setSelectionMode(QAbstractItemView.SingleSelection)
        self.table_cylinder_list.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.table_cylinder_list.verticalHeader().setVisible(False)
        self.table_cylinder_list.setHorizontalHeaderLabels(
            QString("Identification;CH4 Concentration (ppm);Uncertainty (%);Used as").split(";"))
        self.table_cylinder_list.setColumnWidth(0, 140)
        self.table_cylinder_list.setColumnWidth(1, 200)
        self.table_cylinder_list.setColumnWidth(2, 180)
        self.input_cylinder_ident = QLineEdit()
        self.input_cylinder_ch4 = QLineEdit()
        self.input_cylinder_uncertainty = QLineEdit()
        self.button_add_cylinder = QPushButton("Add")
        self.button_update_cylinder = QPushButton("Update")
        self.button_delete_cylinder = QPushButton("Delete")
        self.button_exit_cylinder_setting = QPushButton("Exit")
        control_layout = QHBoxLayout()
        control_layout.addWidget(self.button_add_cylinder)
        control_layout.addStretch(1)
        control_layout.addWidget(self.button_delete_cylinder)
        control_layout.addStretch(1)
        control_layout.addWidget(self.button_update_cylinder)
        control_layout.addStretch(1)
        control_layout.addWidget(self.button_exit_cylinder_setting)
        info_layout = QFormLayout()
        info_layout.addRow("Identification", self.input_cylinder_ident)
        info_layout.addRow("CH4 concentration (ppm)", self.input_cylinder_ch4)
        info_layout.addRow("Uncertainty (%)", self.input_cylinder_uncertainty)
        cylinder_layout = QGridLayout()
        cylinder_layout.setColumnStretch(0,1)
        cylinder_layout.setColumnStretch(2,1)
        cylinder_layout.setRowStretch(0,1)
        cylinder_layout.addWidget(QLabel("Available Cylinders"),1,1,Qt.AlignHCenter)
        cylinder_layout.addWidget(self.table_cylinder_list,2,1,Qt.AlignHCenter)
        cylinder_layout.addLayout(info_layout,3,1,Qt.AlignHCenter)
        cylinder_layout.addLayout(control_layout,4,1,Qt.AlignHCenter)
        cylinder_layout.setRowStretch(5,1)
        self.cylinder_frame.setLayout(cylinder_layout)
            
        main_layout = QVBoxLayout()
        main_layout.addWidget(self.top_frame)
        main_layout.addWidget(self.wizard_frame)
        main_layout.addWidget(self.report_frame)
        main_layout.addWidget(self.login_frame)
        main_layout.addWidget(self.cylinder_frame)
        
        central_widget = QWidget()
        central_widget.setLayout(main_layout)
        self.setCentralWidget(central_widget)
        
        self.report_frame.hide()
        self.top_frame.hide()
        self.wizard_frame.hide()
        self.cylinder_frame.hide()
        
    def set_connections(self):
        self.measurement_timer.timeout.connect(self.measurement)
        self.button_skip_step.clicked.connect(self.skip_step)
        self.button_next_step.clicked.connect(self.next_step)
        self.button_cancel_process.clicked.connect(self.cancel_process)
        self.button_exit.clicked.connect(self.exit_program)
        self.input_password.returnPressed.connect(self.user_login)
        self.button_user_login.clicked.connect(self.user_login)
        self.button_cancel_login.clicked.connect(self.cancel_login)
        self.table_cylinder_list.clicked.connect(self.select_cylinder_from_table)
        self.button_add_cylinder.clicked.connect(self.add_cylinder)
        self.button_delete_cylinder.clicked.connect(self.delete_cylinder)
        self.button_update_cylinder.clicked.connect(self.update_cylinder_info)
        self.button_exit_cylinder_setting.clicked.connect(self.exit_cylinder_setting)
        self.button_edit_cylinder.clicked.connect(self.edit_cylinder)