# autogenerated by PyBuilder

def versionString():
    return 'i2000-1.0.0.12 (295943f3)'

def versionNumString():
    return '1.0.0.12'

def buildType():
    # Empty string indicates official release
    return ''
