# autogenerated by PyBuilder

def versionString():
    return 'si2000-1.0.0.0 (e912d7b3)'

def versionNumString():
    return '1.0.0.0'

def buildType():
    # Empty string indicates official release
    return ''
