syncList = \
[("co2_conc", "co2_conc_sync", "species", 10),
 ("co2_conc_dry", "co2_conc_dry_sync", "species", 10),
 ("ch4_conc", "ch4_conc_sync", "species", 25),
 ("ch4_conc_dry", "ch4_conc_dry_sync", "species", 25),
 ("h2o_conc", "h2o_conc_sync", "species", 28),
 ("solenoid_valves", "solenoid_valves_sync", None, None),
 ("DasTemp", "DasTemp_sync", None, None),
 ("CavityPressure", "CavityPressure_sync", None, None),
 ("MPVPosition", "MPVPosition_sync", None, None),
 ("OutletValve", "OutletValve_sync", None, None),
 ("CavityTemp", "CavityTemp_sync", None, None),
 ("WarmBoxTemp", "WarmBoxTemp_sync", None, None),
 ("EtalonTemp", "EtalonTemp_sync", None, None),
 ("ANEMOMETER_UX", "ANEMOMETER_UX_sync", None, None),
 ("ANEMOMETER_UY", "ANEMOMETER_UY_sync", None, None),
 ("ANEMOMETER_UZ", "ANEMOMETER_UZ_sync", None, None),
 ("ANEMOMETER_C", "ANEMOMETER_C_sync", None, None),
 ("GPS_TIME", "GPS_TIME_sync", None, None),
 ("GPS_ABS_LAT", "GPS_ABS_LAT_sync", None, None),
 ("GPS_REL_LAT", "GPS_REL_LAT_sync", None, None),
 ("GPS_FIT", "GPS_FIT_sync", None, None),
 ("GPS_ABS_LONG", "GPS_ABS_LONG_sync", None, None),
 ("GPS_REL_LONG", "GPS_REL_LONG_sync", None, None),
 ]
