#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Sun Oct 30 16:28:27 2011

import wx
from ReceiverFrameGui import ReceiverFrameGui

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_receiver = ReceiverFrameGui(None, -1, "")
    app.SetTopWindow(frame_receiver)
    frame_receiver.Show()
    app.MainLoop()
