#!/bin/bash
sudo docker run -d -P -p 0.0.0.0:2222:22 -v /home/picarro/Github/hostDocker:/hostRepo -v /home/picarro/Github/hostDocker/src/main/python:/Picarro/G2000 --privileged -v /dev/bus/usb:/dev/bus/usb g2000
