#!/usr/bin/env python

import os
import time
import shutil

# Kill host software if it's running
host_software_components = ["AlarmSystem", "Archiver",\
        "Controller", "ControlBridge", "DataLogger", \
        "DataManager", "DataManagerPublisher", "Driver",\
        "DriverSimulator","EventManager", "Fitter",\
        "HostStartup", "InstMgr", "MobileKitMonitor", \
        "MeasSystem", "QuickGui", "RDFreqConverter",\
        "RestartSurveyor", "RestartSupervisor", "SampleManager", \
        "Serial2Socket", "SpectrumCollector", "SQLiteServer",\
        "StopSupervisor", "Supervisor", "SupervisorLauncher" \
                            ]

# Search the list for PIDs that contain the name of the Python
# code and kill them before installing new code.
# pgrep is a version of grep that searches the process table
# and returns a matching PID.
#
for c in host_software_components:
    os.system("kill $(pgrep -f %s)" %c)


# Backup instrConfig if it already exists
instr_config = "/home/picarro/SI2000/InstrConfig"
if os.path.isdir(instr_config):
    root_dir = "/home/picarro/SI2000"
    # make sure there is no 'active' instrConfig folder left over by last installation
    for folder in os.listdir(root_dir):
        if folder.startswith("InstrConfig") and folder.endswith("_active"):
            os.rename(os.path.join(root_dir, folder), os.path.join(root_dir, folder[:-7]))
    # backup instrConfig
    config_backup = os.path.join(root_dir, time.strftime("InstrConfig_%Y%m%d_%H%M%S_active"))
    shutil.copytree(instr_config, config_backup)
    os.system("chown -R picarro.picarro " + config_backup)
