AnalyzerSwitcher.py -a AEDS
::AnalyzerSwitcher.py -a BFADS
::AnalyzerSwitcher.py -a CBDS
::AnalyzerSwitcher.py -a CFADS
::AnalyzerSwitcher.py -a CFBDS
::AnalyzerSwitcher.py -a CFDDS
::AnalyzerSwitcher.py -a CFEDS
::AnalyzerSwitcher.py -a CFFDS
::AnalyzerSwitcher.py -a CFGDS
::AnalyzerSwitcher.py -a CFHADS
::AnalyzerSwitcher.py -a CFHDS
::AnalyzerSwitcher.py -a CFIDS
::AnalyzerSwitcher.py -a CFJDS
::AnalyzerSwitcher.py -a CFKADS
::AnalyzerSwitcher.py -a CFKBDS
::AnalyzerSwitcher.py -a CHADS
::AnalyzerSwitcher.py -a CKADS
::AnalyzerSwitcher.py -a DFADS
::AnalyzerSwitcher.py -a FCDS
::AnalyzerSwitcher.py -a FDDS
::AnalyzerSwitcher.py -a GFADS
::AnalyzerSwitcher.py -a HBDS
::AnalyzerSwitcher.py -a HIDS
::AnalyzerSwitcher.py -a HKDS
::AnalyzerSwitcher.py -a JADS
::AnalyzerSwitcher.py -a JFAADS
::AnalyzerSwitcher.py -a MADS
::AnalyzerSwitcher.py -a NBDS