#!/bin/bash
#sudo docker run -d -P -p 0.0.0.0:2222:22 -p 0.0.0.0:40000:40000 -p 0.0.0.0:5901:5901 -v ~/Github/hostDocker:/hostRepo -v ~/Github/hostDocker/src/main/python:/Picarro/G2000 --privileged -v /dev/bus/usb:/dev/bus/usb g2000-lubuntu /bin/bash -c "/usr/sbin/sshd -D"
sudo docker run -d -P -p 0.0.0.0:2222:22 -p 0.0.0.0:40000:40000 -p 0.0.0.0:5901:5901 -v ~/Github/hostDocker:/hostRepo -v ~/Github/hostDocker/src/main/python:/Picarro/G2000 --privileged -v /dev/bus/usb:/dev/bus/usb picarrodocker/g2000_lubuntu
