{
 "title": "Aggregation Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Variable", "query": "search" },
   {
    "name": "Aggregation",
    "query": "15s, 1m, 5m, 15m, 1h, 4h, 12h, 24h"
   }
  ]
 },
 "panels": [
  {
   "title": "Count records from crds",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Count records in time window",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Field keys and types",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fields from JSON data source",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "targets": [
    { "target": "select metric", "type": "timeseries" }
   ]
  },
  {
   "title": "Tags from JSON data source",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "targets": [
    { "target": "select metric", "type": "timeseries" }
   ]
  },
  {
   "title": "$Variable (auto time resolution)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "$Variable", "type": "timeseries" }
   ]
  },
  {
   "title": "$Variable ($Aggregation aggregation)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "repeat": "Aggregation",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^crds_$Aggregation$/",
     "query": "SELECT mean(\"mean_$Variable\"), max(\"max_$Variable\"), min(\"min_$Variable\") FROM /^crds_$Aggregation$/ WHERE time>=[[__from]]ms-$Aggregation AND time<[[__to]]ms+$Aggregation GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean_$Variable" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "max_$Variable" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "min_$Variable" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  }
 ]
}