#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Thu Apr 09 11:58:11 2009

import wx

# begin wxGlade: extracode
from ParameterGrid import ParameterGrid

# end wxGlade

class ParameterDialogGui(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ParameterDialogGui.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.parameterGrid = ParameterGrid(self, wx.ID_ANY)
        self.commitButton = wx.Button(self.panel_1, -1, "Commit")
        self.applyButton = wx.Button(self.panel_1, -1, "Apply")
        self.discardButton = wx.Button(self.panel_1, -1, "Discard")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onCommit, self.commitButton)
        self.Bind(wx.EVT_BUTTON, self.onApply, self.applyButton)
        self.Bind(wx.EVT_BUTTON, self.onDiscard, self.discardButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ParameterDialogGui.__set_properties
        self.SetTitle("dialog_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ParameterDialogGui.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.parameterGrid, 1, wx.EXPAND, 0)
        sizer_2.Add((5, 20), 1, 0, 0)
        sizer_2.Add(self.commitButton, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_2.Add(self.applyButton, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_2.Add(self.discardButton, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_2.Add((5, 20), 1, 0, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 0, wx.EXPAND, 20)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def onCommit(self, event): # wxGlade: ParameterDialogGui.<event_handler>
        print "Event handler `onCommit' not implemented!"
        event.Skip()

    def onApply(self, event): # wxGlade: ParameterDialogGui.<event_handler>
        print "Event handler `onApply' not implemented!"
        event.Skip()

    def onDiscard(self, event): # wxGlade: ParameterDialogGui.<event_handler>
        print "Event handler `onDiscard' not implemented!"
        event.Skip()

# end of class ParameterDialogGui

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = ParameterDialogGui(None, wx.ID_ANY, "")
    app.SetTopWindow(dialog_1)
    dialog_1.ShowModal()
