#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Wed Apr 29 09:22:48 2009

import wx

# begin wxGlade: extracode
from Host.Common.GraphPanel import GraphPanel
from Host.Common.GraphPanel import GraphPanel
# end wxGlade



class LaserPanelGui(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LaserPanelGui.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.temperatureGraph = GraphPanel(self, wx.ID_ANY)
        self.tecGraph = GraphPanel(self, wx.ID_ANY)
        self.currentGraph = GraphPanel(self, wx.ID_ANY)
        self.clearButton = wx.Button(self.panel_1, wx.ID_CLEAR, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onClear, id=wx.ID_ANY)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LaserPanelGui.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LaserPanelGui.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.temperatureGraph, 1, wx.EXPAND, 0)
        sizer_2.Add(self.tecGraph, 1, wx.EXPAND, 0)
        sizer_2.Add(self.currentGraph, 1, wx.EXPAND, 0)
        sizer_3.Add(self.clearButton, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_3.Add((20, 20), 1, 0, 0)
        self.panel_1.SetSizer(sizer_3)
        sizer_2.Add(self.panel_1, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        # end wxGlade

    def onClear(self, event): # wxGlade: LaserPanelGui.<event_handler>
        print "Event handler `onClear' not implemented!"
        event.Skip()

# end of class LaserPanelGui


class CommandLogPanelGui(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CommandLogPanelGui.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.panel_7 = wx.Panel(self, wx.ID_ANY)
        self.panel_8 = wx.Panel(self.panel_7, wx.ID_ANY)
        self.streamFileCheckbox = wx.CheckBox(self.panel_7, wx.ID_ANY, "Stream File")
        self.streamFileTextCtrl = wx.TextCtrl(self.panel_7, wx.ID_ANY, "")
        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        self.panel_3 = wx.Panel(self, wx.ID_ANY)
        self.panel_4 = wx.Panel(self, wx.ID_ANY)
        self.panel_5 = wx.Panel(self, wx.ID_ANY)
        self.panel_6 = wx.Panel(self, wx.ID_ANY)
        self.logListCtrl = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_REPORT|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_CHECKBOX, self.onSteamFileCheck, id=wx.ID_ANY)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CommandLogPanelGui.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CommandLogPanelGui.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(2, 3, 0, 0)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.panel_8, 1, wx.EXPAND, 0)
        sizer_5.Add(self.streamFileCheckbox, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.streamFileTextCtrl, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(sizer_5, 0, wx.ALL|wx.EXPAND, 6)
        self.panel_7.SetSizer(sizer_4)
        grid_sizer_1.Add(self.panel_7, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_5, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_6, 1, wx.EXPAND, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_1.Add(self.logListCtrl, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        # end wxGlade

    def onSteamFileCheck(self, event): # wxGlade: CommandLogPanelGui.<event_handler>
        print "Event handler `onSteamFileCheck' not implemented!"
        event.Skip()

# end of class CommandLogPanelGui


class HotBoxPanelGui(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: HotBoxPanelGui.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.temperatureGraph = GraphPanel(self, wx.ID_ANY)
        self.tecGraph = GraphPanel(self, wx.ID_ANY)
        self.heaterGraph = GraphPanel(self, wx.ID_ANY)
        self.clearButton = wx.Button(self.panel_1, wx.ID_CLEAR, "")
        self.cavityTemperatureCheckbox = wx.CheckBox(self.panel_1, wx.ID_ANY, "Cavity Temperature")
        self.heatsinkTemperatureCheckbox = wx.CheckBox(self.panel_1, wx.ID_ANY, "Heatsink Temperature")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onClear, id=wx.ID_ANY)
        self.Bind(wx.EVT_CHECKBOX, self.onWaveformSelectChanged, id=wx.ID_ANY)
        self.Bind(wx.EVT_CHECKBOX, self.onWaveformSelectChanged, id=wx.ID_ANY)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: HotBoxPanelGui.__set_properties
        self.cavityTemperatureCheckbox.SetValue(1)
        self.heatsinkTemperatureCheckbox.SetValue(1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: HotBoxPanelGui.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.temperatureGraph, 1, wx.EXPAND, 0)
        sizer_2.Add(self.tecGraph, 1, wx.EXPAND, 0)
        sizer_2.Add(self.heaterGraph, 1, wx.EXPAND, 0)
        sizer_3.Add(self.clearButton, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 15)
        sizer_6.Add(self.cavityTemperatureCheckbox, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_6.Add(self.heatsinkTemperatureCheckbox, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_3)
        sizer_2.Add(self.panel_1, 0, 0, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        # end wxGlade

    def onClear(self, event): # wxGlade: HotBoxPanelGui.<event_handler>
        print "Event handler `onClear' not implemented!"
        event.Skip()

    def onWaveformSelectChanged(self, event): # wxGlade: HotBoxPanelGui.<event_handler>
        print "Event handler `onWaveformSelectChanged' not implemented!"
        event.Skip()

# end of class HotBoxPanelGui


