"""
File name: PumpDataProcessorFrame.py
Purpose: The GUI frame for PumpDataProcessor.py

File History:
    2010-03-12 alex  Remove the "remove spikes" function
    2014-03-31 tw    Extracted from WinXP release
"""

import wx
import wx.grid

class PumpDataProcessorFrame(wx.Frame):

    def __init__(self, *args, **kwds):
        wx.Frame.__init__(self, *args, **kwds)
        self.panel1 = wx.Panel(self, -1, style=wx.SUNKEN_BORDER | wx.TAB_TRAVERSAL | wx.ALWAYS_SHOW_SB)
        self.panel2 = wx.Panel(self, -1, style=wx.SUNKEN_BORDER | wx.TAB_TRAVERSAL | wx.ALWAYS_SHOW_SB)
        self.panel3 = wx.Panel(self, -1, style=wx.SUNKEN_BORDER | wx.TAB_TRAVERSAL | wx.ALWAYS_SHOW_SB)
        self.SetTitle('Syringe Pump Data Processor')
        self.panel1.SetBackgroundColour('#E0FFFF')
        self.panel2.SetBackgroundColour('#BDEDFF')
        self.panel3.SetBackgroundColour('#85B24A')
        self.frameMenubar = wx.MenuBar()
        self.iFile = wx.Menu()
        self.iPlot = wx.Menu()
        self.iHelp = wx.Menu()
        self.frameMenubar.Append(self.iFile, 'File')
        self.idLoadFile = wx.NewId()
        self.iLoadFile = wx.MenuItem(self.iFile, self.idLoadFile, 'Load data files', '', wx.ITEM_NORMAL)
        self.iFile.AppendItem(self.iLoadFile)
        self.frameMenubar.Append(self.iPlot, 'Plot')
        self.idShowPlots = wx.NewId()
        self.iShowPlots = wx.MenuItem(self.iPlot, self.idShowPlots, 'Show all plots', '', wx.ITEM_NORMAL)
        self.iPlot.AppendItem(self.iShowPlots)
        self.idClosePlots = wx.NewId()
        self.iClosePlots = wx.MenuItem(self.iPlot, self.idClosePlots, 'Close all plots', '', wx.ITEM_NORMAL)
        self.iPlot.AppendItem(self.iClosePlots)
        self.frameMenubar.Append(self.iHelp, 'Help')
        self.idAbout = wx.NewId()
        self.iAbout = wx.MenuItem(self.iHelp, self.idAbout, 'About Syringe Pump Data Processor', '', wx.ITEM_NORMAL)
        self.iHelp.AppendItem(self.iAbout)
        self.SetMenuBar(self.frameMenubar)
        self.labelLiquid = wx.StaticText(self.panel1, -1, 'Liquid Data Analysis')
        self.labelLiquid.SetFont(wx.Font(10, wx.DEFAULT, style=wx.NORMAL, weight=wx.BOLD))
        self.labelLiquidStartTime = wx.StaticText(self.panel1, -1, 'Start Time (minutes after the beginning of measurement)')
        self.labelLiquidEndTime = wx.StaticText(self.panel1, -1, 'End Time (minutes before the end of measurement)')
        self.labelNumOverlaps = wx.StaticText(self.panel1, -1, 'Maximum number of overlapping plots')
        self.labelVapor = wx.StaticText(self.panel2, -1, 'Vapor Data Analysis')
        self.labelVapor.SetFont(wx.Font(10, wx.DEFAULT, style=wx.NORMAL, weight=wx.BOLD))
        self.labelVaporStartTime = wx.StaticText(self.panel2, -1, 'Start Time (minutes after the beginning of measurement)')
        self.labelVaporEndTime = wx.StaticText(self.panel2, -1, 'End Time (minutes before the end of measurement)')
        self.labelVaporWinSize = wx.StaticText(self.panel2, -1, 'Averaging Window Size (minutes)')
        self.labelFooter = wx.StaticText(self.panel3, -1, 'Copyright Picarro, Inc. 1999-2014', style=wx.ALIGN_CENTER)
        self.gridLiquidStartTime = wx.grid.Grid(self.panel1, -1)
        self.gridLiquidStartTime.CreateGrid(3, 2)
        self.gridLiquidStartTime.SetRowLabelSize(90)
        self.gridLiquidStartTime.SetColLabelSize(20)
        self.gridLiquidStartTime.SetLabelFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ''))
        for colIdx in range(2):
            self.gridLiquidStartTime.SetColLabelValue(colIdx, 'Pump%d' % (colIdx + 1))
            self.gridLiquidStartTime.SetColSize(colIdx, 150)
            for rowIdx in range(3):
                self.gridLiquidStartTime.SetRowLabelValue(rowIdx, 'Conc%d' % (rowIdx + 1))
                self.gridLiquidStartTime.SetRowSize(rowIdx, 20)
                self.gridLiquidStartTime.SetCellValue(rowIdx, colIdx, '5.0')

        self.textCtrlLiquidEndTime = wx.TextCtrl(self.panel1, -1, '0.5')
        self.textCtrlNumOverlaps = wx.TextCtrl(self.panel1, -1, '2')
        self.textCtrlLiquidMsg = wx.TextCtrl(self.panel1, -1, '', style=wx.TE_READONLY | wx.TE_MULTILINE | wx.TE_AUTO_URL | wx.TE_RICH)
        self.textCtrlLiquidMsg.SetMinSize((390, 80))
        self.textCtrlVaporStartTime = wx.TextCtrl(self.panel2, -1, '5.0')
        self.textCtrlVaporEndTime = wx.TextCtrl(self.panel2, -1, '0.5')
        self.textCtrlVaporWinSize = wx.TextCtrl(self.panel2, -1, '0.5')
        self.textCtrlVaporMsg = wx.TextCtrl(self.panel2, -1, '', style=wx.TE_READONLY | wx.TE_MULTILINE | wx.TE_AUTO_URL | wx.TE_RICH2)
        self.textCtrlVaporMsg.SetMinSize((390, 80))
        self.procLiquidButton = wx.Button(self.panel1, -1, 'Process', size=(100, 22))
        self.procVaporButton = wx.Button(self.panel2, -1, 'Process', size=(100, 22))
        self.processButton = wx.Button(self.panel3, -1, 'Process', size=(100, 22))
        self.closeButton = wx.Button(self.panel3, wx.ID_CLOSE, '', size=(100, 22))
        self.procLiquidButton.SetBackgroundColour(wx.Colour(237, 228, 199))
        self.procVaporButton.SetBackgroundColour(wx.Colour(237, 228, 199))
        self.processButton.SetBackgroundColour(wx.Colour(237, 228, 199))
        self.closeButton.SetBackgroundColour(wx.Colour(237, 228, 199))
        self.__do_layout()

    def __do_layout(self):
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3_inner = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(-1, 2)
        grid_sizer_2 = wx.FlexGridSizer(-1, 2)
        grid_sizer_1.Add(self.labelLiquid, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_1.Add(self.procLiquidButton, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_1.Add(self.labelLiquidStartTime, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add((292, -1))
        grid_sizer_2.Add((-1, -1))
        grid_sizer_2.Add(self.labelLiquidEndTime, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.textCtrlLiquidEndTime, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.labelNumOverlaps, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.textCtrlNumOverlaps, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add((-1, 10))
        sizer_5.Add(self.gridLiquidStartTime, 1, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)
        sizer_1.Add(grid_sizer_1, 0)
        sizer_1.Add(sizer_5, 0)
        sizer_1.Add(grid_sizer_2, 0)
        sizer_1.Add(self.textCtrlLiquidMsg, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 10)
        self.panel1.SetSizer(sizer_1)
        grid_sizer_2 = wx.FlexGridSizer(-1, 2)
        grid_sizer_2.Add(self.labelVapor, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.procVaporButton, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.labelVaporStartTime, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.textCtrlVaporStartTime, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.labelVaporEndTime, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.textCtrlVaporEndTime, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.labelVaporWinSize, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add(self.textCtrlVaporWinSize, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_2.Add((-1, 10))
        sizer_2.Add(grid_sizer_2, 0)
        sizer_2.Add(self.textCtrlVaporMsg, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 10)
        self.panel2.SetSizer(sizer_2)
        sizer_3_inner.Add((180, 20))
        sizer_3_inner.Add(self.processButton, 0, wx.TOP | wx.BOTTOM, 10)
        sizer_3_inner.Add((20, 20))
        sizer_3_inner.Add(self.closeButton, 0, wx.TOP | wx.BOTTOM, 10)
        sizer_3.Add(sizer_3_inner, 0)
        sizer_3.Add(self.labelFooter, 0, wx.EXPAND | wx.BOTTOM, 5)
        self.panel3.SetSizer(sizer_3)
        sizer_4.Add(self.panel1, 0, wx.EXPAND, 0)
        sizer_4.Add(self.panel2, 0, wx.EXPAND, 0)
        sizer_4.Add(self.panel3, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()


if __name__ == '__main__':
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame = PumpDataProcessorFrame(None, -1, '')
    app.SetTopWindow(frame)
    frame.Show()
    app.MainLoop()