#!/bin/bash

# BASH script that returns an echo one character at a time.
# It requires an argument to be called upon execution.
# Example: "./typed-echo 'Howdy doody, partner!'"
# Be sure to put your string inside single quotes.
# Double quotes will allow for exit characters to cause issues.

arg=${@}
for (( i=0; i < ${#arg}; i+=1 )); do #${#arg} is the length of the string
echo -n "${arg:$i:1}"
random1=`shuf -i500-1000 -n1`
random2=`shuf -i1-299 -n1`
randomSleep="$((${random1}-${random2}))"
sleepms="0.0${randomSleep}"
sleep ${sleepms}
done
echo
