#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Fri Mar 17 13:45:07 2017

import wx, time, thread, serial

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.Current = wx.StaticText(self, -1, "Measured Current", style=wx.ALIGN_CENTRE)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("4-20 Current Meter ")
        self.SetSize((703, 300))
        self.SetBackgroundColour(wx.Colour(180, 255, 201))
        self.Current.SetMinSize((450, 200))
        self.Current.SetBackgroundColour(wx.Colour(217, 255, 255))
        self.Current.SetFont(wx.Font(28, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.Current, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade
        
        
class CurrentMeter(MyFrame):
    def __init__(self, *args, **kwds):
        MyFrame.__init__(self, *args, **kwds)
        
        try:
            self.ser = serial.Serial('COM10', timeout = 5)
        except:
            print "Can not connect to the port."
            
        thread.start_new_thread(self.update, ())
        
    def update(self):
        while 1:
            self.ser.write(b'meas:curr:dc?\r')
            bytesToRead = self.ser.inWaiting()
            s = self.ser.read(bytesToRead)
            if s != '':
                self.Current.SetLabel(s[:18] + ' ')
            time.sleep(1)
        
    
    

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    ui = CurrentMeter(None, -1, "")
    app.SetTopWindow(ui)
    ui.Show()
    app.MainLoop()
