#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Fri Aug 31 16:07:49 2012

import wx

# begin wxGlade: extracode
# end wxGlade


class ExFrame1Gui(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ExFrame1Gui.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_background = wx.Panel(self, -1)
        self.label_input = wx.StaticText(self.panel_background, -1, "Input")
        self.text_ctrl_input = wx.TextCtrl(self.panel_background, -1, "")
        self.label_output = wx.StaticText(self.panel_background, -1, "Output")
        self.text_ctrl_output = wx.TextCtrl(self.panel_background, -1, "")
        self.button_evaluate = wx.Button(self.panel_background, -1, "Evaluate")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onEvaluate, self.button_evaluate)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ExFrame1Gui.__set_properties
        self.SetTitle("Example GUI")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ExFrame1Gui.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.label_input, 0, wx.ALL, 5)
        sizer_2.Add(self.text_ctrl_input, 0, wx.ALL | wx.EXPAND, 5)
        sizer_2.Add(self.label_output, 0, wx.ALL, 5)
        sizer_2.Add(self.text_ctrl_output, 0, wx.ALL | wx.EXPAND, 5)
        sizer_2.Add(self.button_evaluate, 0, wx.ALL | wx.EXPAND, 10)
        self.panel_background.SetSizer(sizer_2)
        sizer_1.Add(self.panel_background, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def onEvaluate(self, event):  # wxGlade: ExFrame1Gui.<event_handler>
        print "Event handler `onEvaluate' not implemented!"
        event.Skip()

# end of class ExFrame1Gui
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_example = ExFrame1Gui(None, -1, "")
    app.SetTopWindow(frame_example)
    frame_example.Show()
    app.MainLoop()
