# -*- coding: UTF8 -*-
#
# generated by wxGlade 0.7.0 on Sun Mar 01 10:17:30 2015
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LaserControlPanelGui(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LaserControlPanelGui.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.splitter = wx.SplitterWindow(self, wx.ID_ANY, style=wx.SP_3D | wx.SP_BORDER)
        self.splitter_pane_1 = wx.Panel(self.splitter, wx.ID_ANY)
        self.label_select_level = wx.StaticText(self.splitter_pane_1, wx.ID_ANY, _("Select current level"))
        self.list_box_levels = wx.ListBox(self.splitter_pane_1, wx.ID_ANY, choices=[])
        self.label_level_entry = wx.StaticText(self.splitter_pane_1, wx.ID_ANY, _("Enter list of levels"))
        self.text_ctrl_level_entry = wx.TextCtrl(self.splitter_pane_1, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.splitter_pane_2 = wx.Panel(self.splitter, wx.ID_ANY)
        self.label_updated_level = wx.StaticText(self.splitter_pane_2, wx.ID_ANY, _("Updated level"))
        self.text_ctrl_updated_level = wx.TextCtrl(self.splitter_pane_2, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.label_slope_factor = wx.StaticText(self.splitter_pane_2, wx.ID_ANY, _("Slope factor"))
        self.text_ctrl_slope_factor = wx.TextCtrl(self.splitter_pane_2, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.label_time_between_steps = wx.StaticText(self.splitter_pane_2, wx.ID_ANY, _("Time between steps"))
        self.text_ctrl_time_between_steps = wx.TextCtrl(self.splitter_pane_2, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.label_upper_window = wx.StaticText(self.splitter_pane_2, wx.ID_ANY, _("Upper window"))
        self.text_ctrl_upper_window = wx.TextCtrl(self.splitter_pane_2, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.label_lower_window = wx.StaticText(self.splitter_pane_2, wx.ID_ANY, _("Lower window"))
        self.text_ctrl_lower_window = wx.TextCtrl(self.splitter_pane_2, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.label_binning_rd = wx.StaticText(self.splitter_pane_2, wx.ID_ANY, _("# RD for binning"))
        self.text_ctrl_binning_rd = wx.TextCtrl(self.splitter_pane_2, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.checkbox_update_levels = wx.CheckBox(self.splitter_pane_2, wx.ID_ANY, _("Update levels"))
        self.checkbox_update_waveform = wx.CheckBox(self.splitter_pane_2, wx.ID_ANY, _("Update waveform"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX, self.onLevelSelect, self.list_box_levels)
        self.Bind(wx.EVT_TEXT_ENTER, self.onLevelEntryEnter, self.text_ctrl_level_entry)
        self.Bind(wx.EVT_TEXT_ENTER, self.onUpdatedLevelEnter, self.text_ctrl_updated_level)
        self.Bind(wx.EVT_TEXT_ENTER, self.onSlopeFactorEnter, self.text_ctrl_slope_factor)
        self.Bind(wx.EVT_TEXT_ENTER, self.onTimeBetweenStepsEnter, self.text_ctrl_time_between_steps)
        self.Bind(wx.EVT_TEXT_ENTER, self.onUpperWindowEnter, self.text_ctrl_upper_window)
        self.Bind(wx.EVT_TEXT_ENTER, self.onLowerWindowEnter, self.text_ctrl_lower_window)
        self.Bind(wx.EVT_TEXT_ENTER, self.onBinningRdEnter, self.text_ctrl_binning_rd)
        self.Bind(wx.EVT_CHECKBOX, self.onUpdateLevelsCheck, self.checkbox_update_levels)
        self.Bind(wx.EVT_CHECKBOX, self.onUpdateWaveformCheck, self.checkbox_update_waveform)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LaserControlPanelGui.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LaserControlPanelGui.__do_layout
        sizer_panel = wx.BoxSizer(wx.VERTICAL)
        sizer_pane_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_buttons = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(12, 2, 0, 0)
        sizer_pane_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_pane_1.Add(self.label_select_level, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 5)
        sizer_pane_1.Add(self.list_box_levels, 2, wx.EXPAND, 0)
        sizer_pane_1.Add(self.label_level_entry, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 5)
        sizer_pane_1.Add(self.text_ctrl_level_entry, 1, wx.EXPAND, 0)
        self.splitter_pane_1.SetSizer(sizer_pane_1)
        grid_sizer_1.Add(self.label_updated_level, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_updated_level, 0, wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.Add(self.label_slope_factor, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_slope_factor, 0, wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.Add(self.label_time_between_steps, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_time_between_steps, 0, wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.Add(self.label_upper_window, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_upper_window, 0, wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.Add(self.label_lower_window, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_lower_window, 0, wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.Add(self.label_binning_rd, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_binning_rd, 0, wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.AddGrowableCol(1)
        sizer_pane_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_buttons.Add((20, 20), 1, 0, 0)
        sizer_buttons.Add(self.checkbox_update_levels, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 10)
        sizer_buttons.Add((20, 20), 1, 0, 0)
        sizer_buttons.Add(self.checkbox_update_waveform, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 10)
        sizer_buttons.Add((20, 20), 1, 0, 0)
        sizer_pane_2.Add(sizer_buttons, 0, wx.EXPAND, 0)
        self.splitter_pane_2.SetSizer(sizer_pane_2)
        self.splitter.SplitVertically(self.splitter_pane_1, self.splitter_pane_2)
        sizer_panel.Add(self.splitter, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_panel)
        sizer_panel.Fit(self)
        self.Layout()
        # end wxGlade

    def onLevelSelect(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onLevelSelect' not implemented!"
        event.Skip()

    def onLevelEntryEnter(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onLevelEntryEnter' not implemented!"
        event.Skip()

    def onUpdatedLevelEnter(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onUpdatedLevelEnter' not implemented!"
        event.Skip()

    def onSlopeFactorEnter(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onSlopeFactorEnter' not implemented!"
        event.Skip()

    def onTimeBetweenStepsEnter(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onTimeBetweenStepsEnter' not implemented!"
        event.Skip()

    def onUpperWindowEnter(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onUpperWindowEnter' not implemented!"
        event.Skip()

    def onLowerWindowEnter(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onLowerWindowEnter' not implemented!"
        event.Skip()

    def onBinningRdEnter(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onBinningRdEnter' not implemented!"
        event.Skip()

    def onUpdateLevelsCheck(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onUpdateLevelsCheck' not implemented!"
        event.Skip()

    def onUpdateWaveformCheck(self, event):  # wxGlade: LaserControlPanelGui.<event_handler>
        print "Event handler 'onUpdateWaveformCheck' not implemented!"
        event.Skip()

# end of class LaserControlPanelGui
